### ISSUE TITLE
cannot clone project in window - file name is too long

### ISSUE THREAD

**Issue by shaiatias** [WebAssembly/binaryen#1020]
Trying to checkout the project in window env.
git spits the following error:

> error: unable to create file test/passes/rereloop_dce_remove-unused-brs_remove-unused-names_simplify-locals-nostructure_vacuum_reorder-locals_coalesce-locals_simplify-locals_reorder-locals_merge-blocks_remove-unused-brs_merge-blocks_vacuum.txt (Filename too long)
error: unable to create file test/passes/rereloop_dce_remove-unused-brs_remove-unused-names_simplify-locals-nostructure_vacuum_reorder-locals_coalesce-locals_simplify-locals_reorder-locals_merge-blocks_remove-unused-brs_merge-blocks_vacuum.wast (Filename too long)

I've also tried to download as zip and extract manually, similar result.

**Comment by binji** [comment]
On Windows, I assume? Looks like that filename is 215 chars, so you should be able to fit it if you clone to a directory with a shorter path. Often when this happens I use [subst](https://technet.microsoft.com/en-us/library/bb491006.aspx) to create a new drive mapping to that directory. That way the directory name is as short as possible.

**Comment by Cellule** [comment]
I am getting a similar issue when using emscripten.
During unzipping binaryen, emscripten gets the following error
```
WARNING:root:retrieving port: binaryen from https://github.com/WebAssembly/binaryen/archive/version_44.zip
WARNING:root:unpacking port: binaryen
ERROR:root:a problem occurred when using an emscripten-ports library. try to run    emcc --clear-ports    and then run this command again
Traceback (most recent call last):
  File "D:\projects\ChakraTool\WasmExprgen\third_party\wasm-exprgen\third_party\emscripten\emcc.py", line 2786, in <module>
    run()
  File "D:\projects\ChakraTool\WasmExprgen\third_party\wasm-exprgen\third_party\emscripten\emcc.py", line 1483, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "D:\projects\ChakraTool\WasmExprgen\third_party\wasm-exprgen\third_party\emscripten\tools\system_libs.py", line 749, in get_ports
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "D:\projects\ChakraTool\WasmExprgen\third_party\wasm-exprgen\third_party\emscripten\tools\ports\binaryen.py", line 21, in get
    ports.fetch_project('binaryen', 'https://github.com/WebAssembly/binaryen/archive/' + TAG + '.zip', 'binaryen-' + TAG)
  File "D:\projects\ChakraTool\WasmExprgen\third_party\wasm-exprgen\third_party\emscripten\tools\system_libs.py", line 686, in fetch_project
    unpack()
  File "D:\projects\ChakraTool\WasmExprgen\third_party\wasm-exprgen\third_party\emscripten\tools\system_libs.py", line 665, in unpack
    z.extractall()
  File "C:\Python27\lib\zipfile.py", line 1043, in extractall
    self.extract(zipinfo, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1031, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1086, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: 'D:\\projects\\ChakraTool\\WasmExprgen\\third_party\\wasm-exprgen\\output\\.emscripten_ports\\binaryen\\binaryen-version_44\\test\\passes\\rereloop_dce_remove-unused-brs_remove-unused-names_coalesce-locals_simplify-locals_reorder-locals_remove-unused-brs_merge-blocks_vacuum.txt'
```
Are those tests files even needed in the package used by emscripten if it's only test files ?

This didn't use to be a problem.
I had to update the version of emscripten because of issue https://github.com/kripken/emscripten/issues/6275 where binaryen would fail to download.
Now it fails to extract because of that new test. Not sure when it was added, I used to have binaryen version 37 and the file wasn't there.

**Comment by kripken** [comment]
Hmm, we don't need those files in emscripten, but what we download is just the github zip of the repo, which includes everything. Maybe we could set up something more sophisticated with just the files we need, but I'm not sure how to do that or how much work it would be.

Alternatively, we could change the test infrastructure. Right now it encodes the passes for the test in the filename. We could move them to a side file instead perhaps.

**Comment by Cellule** [comment]
Looks like the test file has been there for longer than I thought.
It seems my installation process tries to run emscripten up to 5 times to verify.
It always fails the first time because of that file, but everything else has been correctly extracted, so on the second try emscripten doesn't attempt to extract and just goes on with building/running the port.

After updating python on my build machine, it looks like I no longer encounter SSL issue and now my build process silently ignores that error.
I wouldn't call it resolved, but at least I can run binaryen in emscripten again

**Comment by kripken** [comment]
This should be fixed now on master.
