### ISSUE TITLE
binaryen.wasm

### ISSUE THREAD

**Issue by pannous** [WebAssembly/binaryen#1051]
Are there plans for something like a wasm version of binaryen.js?  use case:  compilers running inside of the browser, emitting wasm on the fly. binaryen.js is fine in the beginning, binaryen.wasm would just be faster and more elegant.

**Comment by kripken** [comment]
Yeah, it would be good to do this. We will still need JS though even when the compiled code is wasm (for all the integration, exceptions support, etc.). Also, we will still need the asm.js version as well (as some people might be using binaryen.js in their build system, which might use an older node).

**Comment by codefromthecrypt** [comment]
[wazero](wazero.io/) would definitely appreciate this. Right now people are limited to forking processes which makes less sense when considering the repo is owned by wasm experts. For example, Tinygo has to fork processes for optimization of wasm. if you think about it long enough, it makes no sense because we have an embeddable wasm runtime! cc @gedw99

**Comment by tlively** [comment]
A Wasm build of binaryen.js has been available for a while. Build the `binaryen_wasm` target instead of the `binaryen_js` target: https://github.com/WebAssembly/binaryen/blob/main/CMakeLists.txt#L407.

**Comment by codefromthecrypt** [comment]
can you help what I'm doing wrong?

```bash
$ mkdir emcc-build
$ emcmake cmake -B emcc-build -DCMAKE_BUILD_TYPE=Release -G Ninja
--snip--
$ ninja -C emcc-build binaryen_wasm
--snip--
$ ls emcc-build/bin/
binaryen-lit		binaryen_wasm.js
```

I was expecting to produce a wasm file, not a js one..

**Comment by gedw99** [comment]
this is crazy - i like it :)

**Comment by tlively** [comment]
> I was expecting to produce a wasm file, not a js one

the Wasm build has the same JS API has the JS build, so it produces both a Wasm file and a JS file. Maybe binaryen_wasm.wasm ended up in the wrong directory with your build? I don’t think building into directories other than the current directory is well tested.

**Comment by pannous** [comment]
Since binaryen.wasm is universally portable the project owner could just provide the binary?

**Comment by kripken** [comment]
I think the issue is that `CMakeLists.txt` contains `-sSINGLE_FILE` - we build the wasm into the JS so there is a single file which is simpler for most things. You can edit to remove that one line and rebuild. I attached that result.

However, I don't think you can run that in WASI VMs, since it does depend on the JS. To get something you can run in a WASI VM you'd need to do a port using wasi-libc, probably, but that can't work atm since Binaryen uses C++ exceptions which are not supported there last I heard.

Options here:

1. Remove C++ exceptions from Binaryen. We've wanted to do this for a while but just never gotten around to it. The idea is that the internal interpreter would flow values out using `.breaking` rather than throw and catch. That's already supported for `br` and `switch`, so we just need to do it for traps and wasm exceptions I think.
2. Wait for C++ exceptions support in wasi-libc, or contribute to that.
3. Wait for standalone wasm improvements in emscripten, or contribute to that. (Atm file opening does not work, and depends on JS - that's probably the largest blocker.)

[binaryen_wasm.js.gz](https://github.com/WebAssembly/binaryen/files/9912769/binaryen_wasm.js.gz)

[binaryen_wasm.wasm.gz](https://github.com/WebAssembly/binaryen/files/9912765/binaryen_wasm.wasm.gz)

**Comment by codefromthecrypt** [comment]
I'll open a new issue for standalone binaryen.wasm and cite this in case folks can help. This becomes more critical for the projects I work on towards the end of the year.

**Comment by codefromthecrypt** [comment]
https://github.com/WebAssembly/binaryen/issues/5206

**Comment by codefromthecrypt** [comment]
FWIW I would be in favor of removing exceptions vs making a standalone/wasi target dependent on a phase 3 proposal (exception handling). This increases the accessibility and allows compilers to use this without depending on potentially unimplemented or drifty specs.
