### ISSUE TITLE
wasm-dis detects duplicate exports on names.wast module

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/binaryen#1067]
On this wasm module:

https://github.com/yurydelendik/wasmtext/blob/master/tests/names.wast.2.wasm

which is extracted from names.wast in the wasm testsuite, wasm-dis prints this error:

[parse exception: duplicate export name]Fatal: error in parsing wasm binary

However, the module is valid and does not contain duplicate export names.

**Comment by kripken** [comment]
Looks like it's on `  (export "" (func 0))` - but what does that mean? How can an export have an empty name?

**Comment by sunfishcode** [comment]
An export name is just a sequence of bytes; the sequence may have length 0. Such names couldn't be imported in JS, but under the current rules they're valid in the base wasm language.

**Comment by binji** [comment]
Yeah, I had a similar bug. Seems like kind of a dumb rule tbh, but it's not hard to support.

**Comment by kripken** [comment]
Looking at this more carefully, the issue is that there is an import starting with a null (0), which we read as the empty string, which conflicts since there was already an empty string before.

Binaryen export names are currently Names, which are null-terminated. Not sure if it's worth changing that just for this type of obscure testcase.

**Comment by kripken** [comment]
#1068 makes us show a better error on this case (but does not fix anything).

**Comment by sunfishcode** [comment]
This appears to have been fixed.

```
$ wasm-dis t.wasm
(module
 (type $none_=>_none (func))
 (export "" (func $0))
 (func $0
 )
)

```
