### ISSUE TITLE
Update to C++14?

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/binaryen#1093]
I would have loved to have C++14's simplified `enable_if_t` for #1092. In general C++14 is a minor update but it sands a bunch of rough edges off of C++11.
All* of C++14 is supported by GCC5, clang 3.4, and Visual studio 2015. We already don't test with any compiler earlier than these, so I think we should just document our minimum support based on those versions and use whatever they support. That would even open up a few C++17 features, but we can punt on those for now.

*(according to [cppreference](http://en.cppreference.com/w/cpp/compiler_support) it's everything except  extended constexpr and Member Initializers and Aggregates (NSDMI))

**Comment by dschuff** [comment]
Actually now that I think of it there might be some issues with the C++ stdlib on trusty, which we use on Travis. If we can work any possible Trusty issues out, then we can do this.

**Comment by binji** [comment]
Yeah, I found that at least some C++11 type traits are missing on trusty (libstdc++ 4.8, I believe).

**Comment by sbc100** [comment]
Perhaps its worth upgrading the minimum requirements to Xenial (the latest ubuntu LTS)?

**Comment by am11** [comment]
For Windows, unless there is a major blocker; should the AppVeyor script be updated to validate against VS2017 v15.3 instead of VS 2015.3? It has [better C++ STD support with perf improvements](https://blogs.msdn.microsoft.com/vcblog/2017/08/11/c17-features-and-stl-fixes-in-vs-2017-15-3/) than its predecessors.

For local development, the minimal [Build Tools for Visual Studio 2017](https://www.visualstudio.com/downloads/#other) pulls the required toolchain without needing to install the full IDE. Tools are installable even on headless nano server via command line. Based on project configuration (setting one flag), the compiled binaries can be made compatible with older versions of Windows as well (16 yrs. old XP support is still there), which is no different than what VS2015 and 2013 has to offer at the cost of lesser standards support.

**Comment by dschuff** [comment]
This was done a long time ago.
