### ISSUE TITLE
Non-sense tags/releases 1.37.17, 1.37.18, 1.37.19

### ISSUE THREAD

**Issue by jirutka** [WebAssembly/binaryen#1131]
What are you doing here? The last four tags with version numbers are for exactly the same commit… The last one has been created today. I know it, because I use release-monitoring.org to monitor new releases of binaryen and I got notification about “new release” (1.37.19) just few hours ago.

![binaryen](https://user-images.githubusercontent.com/949228/29369868-1c40c32a-82a4-11e7-9009-9915e3f7d2da.png)

**Comment by juj** [comment]
This is intentional. The tags on Binaryen point to the version of Emscripten that should be used with it. That is, Emscripten 1.37.16, 1.37.17, 1.37.18 and 1.37.19 all use [Binaryen version 34](https://github.com/kripken/emscripten/blob/1.37.19/tools/ports/binaryen.py#L3). The release CI builders snapshot all four toolchain repositories (emscripten, fastcomp, fastcomp-clang, binaryen) on the same tag version to package the appropriate build.

**Comment by jirutka** [comment]
Aha, that’s really confusing, but okay.
