### ISSUE TITLE
BINARYEN_ASYNC_COMPILATION is disabled in SIDE_MODULE / emulated function pointers

### ISSUE THREAD

**Issue by Markyparky56** [WebAssembly/binaryen#1203]
Getting an odd warning from the em++/emcc compilers when trying to compile my code to WebAssembly. Wondering whether this "user option" is my doing or if it's a bug in the current build. Bootstrapped by emsdk following the guidelines [here](http://webassembly.org/getting-started/developers-guide/) and is up to date as far as I can tell.

Warning in full:

    WARNING:root:BINARYEN_ASYNC_COMPILATION requested, but disabled because of user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects

And the build command in full:

    em++ -s BINARYEN_ASYNC_COMPILATION=1 -O3 -s WASM=1 -s SIDE_MODULE=1 -std=c++14 mywasm.cpp -o mywasm.wasm

I get the same warning with both emcc and em++.

**Comment by kripken** [comment]
The error message should be improved, but this is because `SIDE_MODULE`, and dynamic linking more generally as well, is not fully optimized. Currently how it works requires us to disable wasm-only mode, and wasm-only mode is necessary for async compilation.

I thought we had an issue on that, but don't see it. I'll rename this one to that issue, and add it to the dynamic linking project.

**Comment by kripken** [comment]
Oh, I found it, the name didn't focus on dynamic linking. Closing in favor of https://github.com/kripken/emscripten/issues/5567
