### ISSUE TITLE
On exclusively using names in the C-API

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1273]
As a follow-up to @kripken's [comment](https://github.com/WebAssembly/binaryen/pull/1261#discussion_r149478450) in #1261:

> For iteration, perhaps another option is something like a JS API that returns an array of the names, and a C API underneath that does something similar (mallocs a list that must later be freed, and returns it)? Just a suggestion, I'm not sure what is best, but overall I'd like to avoid using indexes (as we have names intentionally, and also, the indexes are internal and do not necessarily match the wasm binary indexes, which could be confusing).

There are two things that bother me about using names exclusively in the C-API:

* Not everything might have a (useful) name, especially when loading binaries without debug info
* In binaryen.js, decoding and encoding UTF8 strings for each invocation comes with quite some overhead

The logical way to avoid any issues there would be to use references / arrays of references (avoiding calling with indexes) instead, while the API could still expose `GetXYByName` methods for convenience. In turn, `BinaryenRemoveExport` and `BinaryenRemoveImport` would have to be renamed to `BinaryenRemoveExportByName` and `BInaryenRemoveImportByName` in favor of the reference versions without such a suffix.

wdyt?

**Comment by kripken** [comment]
Yeah, we should probably focus on using references where possible, for those reasons. Makes sense to rename to `BinaryenRemoveExportByName` as you suggest, too. And modules should provide `getFunction` which receives a name and returns a reference (I don't think it needs to be `getFunctionByName`, as there isn't another way to get a function from the module?)

We can't always, though, as the IR intentionally is designed to use names in specific places, like when creating functions in parallel - if a calls b and b calls a, and we build them in parallel, we don't have refs to give each other (nor do we have an index, we don't know which index they will have), so we must use names there. So creating a call instruction will receive a name.

But otherwise, whenever possible we should use references.

**Comment by kripken** [comment]
Yeah, we should probably focus on using references where possible, for those reasons. Makes sense to rename to `BinaryenRemoveExportByName` as you suggest, too. And modules should provide `getFunction` which receives a name and returns a reference (I don't think it needs to be `getFunctionByName`, as there isn't another way to get a function from the module?)

We can't always, though, as the IR intentionally is designed to use names in specific places, like when creating functions in parallel - if a calls b and b calls a, and we build them in parallel, we don't have refs to give each other (nor do we have an index, we don't know which index they will have), so we must use names there. So creating a call instruction will receive a name.

But otherwise, whenever possible we should use references.

**Comment by kripken** [comment]
Yeah, we should probably focus on using references where possible, for those reasons. Makes sense to rename to `BinaryenRemoveExportByName` as you suggest, too. And modules should provide `getFunction` which receives a name and returns a reference (I don't think it needs to be `getFunctionByName`, as there isn't another way to get a function from the module?)

We can't always, though, as the IR intentionally is designed to use names in specific places, like when creating functions in parallel - if a calls b and b calls a, and we build them in parallel, we don't have refs to give each other (nor do we have an index, we don't know which index they will have), so we must use names there. So creating a call instruction will receive a name.

But otherwise, whenever possible we should use references.

**Comment by dcodeIO** [comment]
[Turned out](https://github.com/WebAssembly/binaryen/pull/1295#discussion_r152412696) that one convention could be:

* Using names in `BinaryenAddSomething`-style functions
* `Something`-references in `BinaryenSomethingAdd`-style ones

Hence closing.
