### ISSUE TITLE
Question about allocating memory on the stack

### ISSUE THREAD

**Issue by justinmchase** [WebAssembly/binaryen#1318]
When I'm looking at the api for `addFunction` I see it accepts a `functionType` and an array of local variable types but I don't see any space for local stack size. It seems like the only types I can have are essentially int/float.

I have figured out how to allocate memory and use local variables as pointers but I'm really wondering if the intention is to allocate everything in linear memory and only have pointers in the function be on the stack?

It does seem simpler to do it that way but I'm wondering if that is optimal or if I'm missing something maybe? I guess if you're going to have heavy async code you're going to have mostly pointers anyway but putting things on the stack is such a common optimization I'm just wondering what the thoughts are around this.

**Comment by kripken** [comment]
Yes, because currently wasm has no stack aside from int/float locals, binaryen doesn't have any explicit C-like stack support yet. So no way to `alloca` X bytes, etc. That leaves the C-like stack to the program itself to handle, binaryen isn't aware of it. The program itself can use a region of linear memory for the C-like stack, managing the stack pointer as necessary, etc.

But I've been thinking we should probably add this at some point, since some optimizations can benefit from it. We use a specific global for the stack pointer, but I think the asm2wasm and wasm backend paths actually give it a different name, so probably we should standardize that. Once that's settled, we can add utilities to binaryen to find stack usage, add `alloca`s, etc. (I'm not sure we'd want to actually add a new `alloca` to binaryen IR, it could just emit reads/writes to that global, as one option.)

One reason I've been thinking of this recently is https://github.com/WebAssembly/binaryen/issues/1312#issuecomment-348409211 where a pass to write locals to the stack was proposed (to support conservative GC, that needs to scan the stack). To make it efficient, we'd probably want to write those locals to the stack, and we'd want a dead store elimination pass that is aware of what stores are to the stack (so that it can eliminate stores not only when something else overwrites them, but also when they are to the stack which is about to be unwound).

**Comment by justinmchase** [comment]
I'll think about that, I suppose I could just malloc a chunk of linear memory and then use it as a stack. That makes sense to me. In fact that sounds fairly desirable.

It may make for a pretty good usecase for having multiple memories. One for stack one for heap. I saw you guys discussing that elsewhere in a different thread. If they were separate then you wouldn't have to malloc your entire stack up front, you could let it grow as much as you wanted in its own memory.

But I'm not sure I would add abstractions like this into binaryen itself, unless wasm natively supports it. I could totally see it as an optional module that many would want to just import and add on but I would add as little as possible to binaryen itself. For example, tying it to a particular implementation of a GC seems like a bad idea, they're not always desirable for one thing and it seems like supporting diversity increases innovation. It would make sense to have a popular GC module that you could just bolt on but I wouldn't put it into binaryen itself, imo.

**Comment by creationix** [comment]
What was the final solution here?

**Comment by tlively** [comment]
Wasm and Binaryen still do not have a concept of in-memory stack, so producers using the Binaryen API would still have to handle allocating and using an in-memory stack themselves.
