### ISSUE TITLE
s2wasm doesn't handle quoted function names

### ISSUE THREAD

**Issue by vvuk** [WebAssembly/binaryen#1327]
s2wasm doesn't handle quoted identifier names; e.g. the following `test.s` file:

```
	.text
	.file	"main"
	.globl	"Tool.Program, Function=null::TestMethod()"
	.type	"Tool.Program, Function=null::TestMethod()",@function
"Tool.Program, Function=null::TestMethod()":
	.result 	i32
	i32.const	$push0=, 5
	.endfunc
.Lfunc_end0:
	.size	"Tool.Program, Function=null::TestMethod()", .Lfunc_end0-"Tool.Program, Function=null::TestMethod()"
```
causes it to blow up:
```
[[parseType:]]:
==========
Function=null::TestMethod()",@function
"Tool.Program, Functi
==========
<crash>
```

I've also had errors in `object_alias` as well.

**Comment by froydnj** [comment]
Is this a wontfix given comments like "[the plan is to avoid the .s format entirely, so llvm would emit a wasm and binaryen's s2wasm wouldn't be needed](https://github.com/WebAssembly/binaryen/issues/1247#issuecomment-339748222)", or will `s2wasm` continue to be supported?

**Comment by dschuff** [comment]
The current plan is to have LLVM output object files, which are linked by lld and then incorporated by emscripten directly. We are pretty close to having this working. We do plan to also have LLVM be capable of producing (and consuming) a text format, which may be similar to the current one (see some discussion about alternatives here https://github.com/WebAssembly/tool-conventions/issues/17). When that happens, s2wasm won't be necessary anymore (because binaryen will not need to as a linker the way s2wasm does, and the linker will output a standard format directly). So we don't plan to invest a lot of work in improving s2wasm.

Having said that, if there's a bug (e.g. in the parser in https://github.com/WebAssembly/binaryen/blob/master/src/s2wasm.h) I'd accept patches to fix it.

If you are using s2wasm in your current project, now might also be a good time to try using LLVM's wasm object file output with lld, as we've recently gotten it feature-complete for C++ support.

**Comment by jakirkham** [comment]
Guess this should be closed as won't fix given `s2wasm` was dropped. ( https://github.com/WebAssembly/binaryen/pull/1607 )
