### ISSUE TITLE
s2wasm creates extra blocks

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/binaryen#139]
For example, test0 in test/llvm_autogenerated/cfg-stackify.s contains no explicit `block`s, but the generated .wast file from s2wasm contains 3 `blocks`: the fake_return_waka123 `block`, another `block` around the entire body, and a `block` around the body of the loop. These blocks aren't required by wasm, and if I edit the .wast file to remove these blocks, binaryen_shell and the spec interpreter both still accept it.

**Comment by kripken** [comment]
1. The `fake_return` block is due to the binaryen ast not having `return`. Last I heard there was still some uncertainty about it being in the final spec, so for now we emulate `return`. If we are sure `return` is here to stay, I can remove that.
2. The second block is for simplicity in building the ast. It's optimized away if you run `-O`, for example. Perhaps we should run the relevant passes automatically in s2wasm?
3. The last is because the binaryen ast has a single child for loops - to make transforms easier, less redundancy (only one node has a list of children). But it accepts as input the short form of course, and I made it emit the short form as well, so that last one is now gone.

**Comment by sunfishcode** [comment]
Re: 1, #524 was closed without any outstanding objections, so I think `return` is here to stay for the foreseeable future.

Re: 2, Is it possible to have it just optimize away the toplevel loop and nothing else?

Re: 3, Thanks! However, does this mean that round-tripping through wasm-as/wasm-dis does not always produce a result identical to the original?

**Comment by kripken** [comment]
1. Ok, sounds good to add return, then. Done.
2. That should also fix the toplevel loop.
3. It did. But wasm-as/wasm-dis changes other stuff too, like names of variables, adding nops for e.g. `br` values per the spec, etc.
