### ISSUE TITLE
Can't compile LLVM IR to WASM

### ISSUE THREAD

**Issue by jwasinger** [WebAssembly/binaryen#1447]
I'm trying to compile a simple C program `int main(int argc, char **argv) { return 0; }` to webassembly.

I built LLVM from master:
```
git clone http://llvm.org/git/llvm.git
cd llvm/tools
git clone http://llvm.org/git/clang.git
cd ../projects
git clone http://llvm.org/git/compiler-rt.git
mkdir ../build
cd ../build
cmake -G Ninja -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly -DLLVM_TARGETS_TO_BUILD= ..
ninja
cd ../..
```

built Binaryen from master,

Then tried to do the compilation:
```
clang -emit-llvm --target=wasm32 -nostdlib -S main.c
llc -march=wasm32 -o main.s main.ll
s2wasm -o main.wast main.s
wasm-as -o main.wasm main.wast
```

`s2wasm` fails with:
```
[[function element:]]:
==========
get_global      $push1=, __stack_pointer
        i32.const       $push2=, 16

==========
Aborted (core dumped)
```

**Comment by jgravelle-google** [comment]
s2wasm doesn't recognize the `get_global` .s syntax from LLVM.
There's actually two wasm triples, `wasm32-unknown-unknown-elf` and `wasm32-unknown-unknown-wasm`. `-wasm` is the default, but s2wasm expects the conventions of `-elf`. So, the command you want for use with s2wasm is:
`clang -emit-llvm --target=wasm32-unknown-unknown-elf -nostdlib -S main.c`

For posterity: `-wasm` is the default when manually invoking clang, because that can output a wasm object file (`.o`), which LLD can link, skipping s2wasm and the assembly format entirely. That's another path to building wasm modules, though it's neither entirely stable nor entirely supported by Emscripten at the moment, so it's not as recommended for use today, unless you're feeling experimental.

**Comment by jwasinger** [comment]
Great!  Now it's working :)
