### ISSUE TITLE
handle float bit reinterpretation functions in wasm2asm

### ISSUE THREAD

**Issue by froydnj** [WebAssembly/binaryen#1458]
The easiest way to handle these is to allocate a static data area of 8 bytes and then do the appropriately-typed stores and loads to that area.  But is it legal to add a new data area to the existing wasm?  Would the compiled wasm potentially know the size of the allocated data area and scribble over our area that we stuck at the end?

If it's not legal to do something like the above, I have a hard time seeing how these instructions could be reasonably translated.

**Comment by kripken** [comment]
Yeah, this is a tricky area. For emscripten output, this is actually already ok, though: we reserve a bunch of bytes in low memory for temporary use, pointed to by `tempDoublePtr`. Even without that, it is always safe to use memory locations 0-8 since we disallow them to be used otherwise.

But for non-emscripten programs, yeah, this is not valid to do in general. An option might be to do a function call out to JS to do it for us. That has the downside of being slower and requiring us to include some JS support code which I don't think we have needed yet.

**Comment by froydnj** [comment]
> But for non-emscripten programs, yeah, this is not valid to do in general. An option might be to do a function call out to JS to do it for us. That has the downside of being slower and requiring us to include some JS support code which I don't think we have needed yet.

Just to be clear, this would make the resulting code almost-asm in the same way that touching `grow_memory` and similar already do?

**Comment by kripken** [comment]
The main code could be valid asm.js, calling out to normal JS is allowed. So we'd have some asm.js and some support JS on the outside which isn't asm.js.

**Comment by krisselden** [comment]
>  we'd have some asm.js and some support JS on the outside

would like to create a function on the outside that you could call for setting the data sections on the buffer you pass into the asmFunc
