### ISSUE TITLE
It seems that s2wasm does not support llvm7's wasm32 format.

### ISSUE THREAD

**Issue by uuhan** [WebAssembly/binaryen#1560]
The command
> clang++-7.0 --target=wasm32 magic.cpp -emit-llvm -o magic.bc -c
> llc-7.0 -march=wasm32 -filetype=asm magic.bc -o magic.s

has the following result (in magic.s):

[magic.s](https://github.com/WebAssembly/binaryen/files/2024016/somecode.txt)

But s2wasm crashes when run with it.

**Comment by jgravelle-google** [comment]
The reason for this is there are two wasm targets in llvm, one made for s2wasm, and one made to better model wasm instructions 1-1. So, calling `s2wasm magic.s`, I get 
```
[[function element:]]:
==========
end_function
.Lfunc_end0:
	.size	magic, .Lfunc_end0-magic
  
==========
Aborted
```
Which is to say it trips over the `end_function`. This is because the `wasm32` target models the end of a function as an instruction, whereas the `wasm32-unknown-unknown-elf` target (the one made for s2wasm) uses the `.endfunc` directive instead. Replacing one with the other, I get:
```
(module
 (table 0 anyfunc)
 (memory $0 1)
 (export "memory" (memory $0))
 (export "magic" (func $magic))
 (func $magic (; 0 ;) (result i32)
  (i32.const 610)
 )
)
```
which works!

So: use `--target=wasm32-unknown-unknown-elf`, and it should Just Work.

(additionally you should be able to just say `clang --target=wasm32-unknown-unknown-elf magic.cpp -S -o magic.s`, if you don't want to look at the intermediate bitcode)

**Comment by uuhan** [comment]
@jgravelle-google Thanks!
