### ISSUE TITLE
wasm-as --source-map issue with backslashes on Windows

### ISSUE THREAD

**Issue by SiggyBar** [WebAssembly/binaryen#1583]
When compiling to WebAssembly with Emscripten version 1.38.3 on Windows, the call stacks produced by emscripten_get_callstack() are not correct for me anymore.

One problem is that backslashes in the generated .wasm.map file are not escaped:
```"base-00\lib\boost\include\boost/none.hpp"```

In the old .js.map file this path would be:
```"base-00\\lib\\boost\\include\\boost/none.hpp"```

I think something else about the source map file also is broken on Windows, because if I manually escape the backslashes in the .wasm.map file then all file paths in the call stack end up using the last entry in the "sources" list.  Maybe there is some other code that also needs a backslash fix?

**Comment by kripken** [comment]
1.38.3 upgraded LLVM, so if this was still ok on 1.38.2, then this is caused by a change in upstream LLVM it seems.

I don't have a windows machine to debug on myself, but this sounds like a debug info issue, so the relevant place might be JSBackend.cpp, specifically `emitDebugInfo()`, https://github.com/kripken/emscripten-fastcomp/blob/cd96346a22e2bcff45f8605a1798ce59f9068029/lib/Target/JSBackend/JSBackend.cpp#L762 Looks like we never added any escaping there, and just trusted LLVM's.

**Comment by RReverser** [comment]
@kripken FWIW this looks like a stale issue that should be now fixed as part of https://github.com/emscripten-core/emscripten/issues/9811.

**Comment by kripken** [comment]
Great, thanks @RReverser !
