### ISSUE TITLE
binaryen.js compilation failures

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1613]
<del>Since https://github.com/WebAssembly/binaryen/pull/1607 was merged,</del> the bot is [reporting issues](https://travis-ci.org/AssemblyScript/binaryen.js/builds/399598917#L5386) with `Module#emitText` and `Module#emitAsmjs` not returning a string but instead printing the respective text to stdout.

Maybe something related to [those lines](https://github.com/WebAssembly/binaryen/blob/master/src/js/binaryen.js-post.js#L1168-L1171)?

**Comment by kripken** [comment]
Oh, oops, that's my fault - it's actually because of https://github.com/kripken/emscripten/pull/6756 , we no longer allow hacks like modifying `Module['print']` dynamically. Fix in #1614

I think we didn't notice it on CI here since it isn't in a tagged version yet - your bot runs incoming, I assume?

**Comment by dcodeIO** [comment]
Great, thanks! And yep, the bot compiles and uses incoming currently.

**Comment by kripken** [comment]
Should be fixed now with that PR just merged.

**Comment by dcodeIO** [comment]
Works again, thanks!
