### ISSUE TITLE
[Feature request] Caching mutable globals to locals in function scope

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#1831]
On some bench which read from globals inside loop this may increase speed on 10% but also increase size a little bit. And obviously should not apply to globals which are involved in atomics operations

**Comment by kripken** [comment]
Interesting, can you share that benchmark?

It's possible this is something we need to ask VMs to optimize as opposed to the toolchain. We'd need good benchmarks in that case.

**Comment by MaxGraey** [comment]
Sure. Here you are:
https://webassembly.studio/?f=7v4mnrr1dar

On my machine
Firefox 65 b5 results:
```
cached globals: 160ms
globals: 195ms
```

Chrome 72.0.3626.17 beta results:
```
cached globals: 193.06591796875ms
globals: 219.97998046875ms
```

**Comment by MaxGraey** [comment]
In my opinion this should be done by toolchain because we have wide range standalone VMs for example which not using extra smart jit for staying simple. But this should be using only for high level optimizations because it could increase produced size.

**Comment by kripken** [comment]
We may want this option for that reason, yeah (since some VMs are not that complex). However, in general this is the kind of optimization that VMs should do IMO since

1. It increases code size (anything that *decreases* code size, the toolchain should definitely do!)
2. The VMs can do better since they know the actual # of registers and the cost of reading a global, and so can reason about whether it's worthwhile caching global values.

I'll try to ask some VM people about this.

What's that LLVM-backed wasm project you mention? wavm? Do they cache, or just they get it automatically from representing the globals as LLVM globals + LLVM's gvn?

**Comment by MaxGraey** [comment]
Wavm which use jit by LLVM definitely the fastest standalone VM for now if trust [this bench](https://github.com/fluencelabs/fluence/blob/master/bench/vm/README.md) but most of VMs doesn't use even JIT or use very simple JIT like Cranelift. But if this is easy to implement in a VM this of course would be more preferable.

**Comment by kripken** [comment]
I looked into this a little, and with little work we should be optimizing this in local-cse and licm, #1840. That covers many common cases, probably. As with licm in general, it shouldn't be on by default, probably, but it's a good option to have.

**Comment by MaxGraey** [comment]
awesome! Thanks
