### ISSUE TITLE
Function table index persistence after optimizations?

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1957]
I am currently thinking about garbage collection again, and one obvious property there is that every managed object must have some sort of id indicating its kind. Now, one convenient way for my specific implementation to accomplish this would be to reuse a function table index (each managed object has an internal gc-specific function anyway) for this id, but this leads me to the question whether this will always keep working after optimizations have been performed?

Imagine a class `Foo` with a `Foo#~gc` function using function table index 1 (= class id 1) and a class `Bar` with `Bar#~gc` using function table index 2 (= class id). In order to distinguish between a `Foo` and a `Bar`, e.g. when doing an `instanceof` check, it must be guaranteed that the function indexes don't become optimized to both be index 1 (as an example) after optimizations, which I imagine could happen if both `~gc` functions happen to look the same? Afaik such an optimization isn't present currently, and I wonder if there are reasons not to do such optimizations, i.e. because the `call_indirect` operand is dynamic which prevents that? Would it be safe to assume that function indexes will "most likely" be retained while Binaryen's passes develop?

For a bit of background: The reason for thinking about something like this in the first place is that it would allow to `call_indirect` a class id directly instead of having to emit an additional function housing a big switch that maps class ids to actual function indexes. It looks appealing to me to avoid additional code this way.

**Comment by kripken** [comment]
It's unlikely generic binaryen optimizations will be able to modify function indexes, I think, since the table can be modified, and also hardcoded indexes can exist in the code as simple constants. For us to do it, we'd need the table to be neither imported nor exported, and for binaryen to support a kind of "relocation info" that marks a constant as "this is a function index".

It's possible we'd add such things eventually, but even if so we could make such table index optimizations optional, so you wouldn't need to worry, I think.
