### ISSUE TITLE
wasm-merge - why it has been deleted

### ISSUE THREAD

**Issue by geloizi** [WebAssembly/binaryen#2174]
Curios why it was decided to remove `wasm-merge` from the project? I s there any alternative "recommended way" of merging wasm modules?

**Comment by tlively** [comment]
We deleted it because we weren't using it and weren't aware of any other uses of it. We now have support for WebAssembly object files in LLVM's lld linker, which provides a much more sophisticated way to merge wasm modules, albeit only those that are valid object files. The use case that is no longer supported is merging separate fully-linked modules together, but it seems that generally it would be better not to do that.

**Comment by Heath123** [comment]
Not all compilers use LLVM or object files though (e.g. AssemblyScript)

**Comment by Heath123** [comment]
This could still be useful for modules that don't use linear memory, or ones that has been specifically compiled to only use a certain segment of memory that won't overlap with anything else

**Comment by Heath123** [comment]
If I need to do this, what should I do? Use an older version of Binaryen?

**Comment by kripken** [comment]
@Heath123 At the moment yes, an older version is the best option.

I do think we should restore `wasm-merge` as various use cases have been accumulating, including yours. Hopefully someone will have time for this soon.
