### ISSUE TITLE
wasm-opt --instrument-memory breaks wasm file compiled by lucet

### ISSUE THREAD

**Issue by orestisfl** [WebAssembly/binaryen#2705]
I have the following file `hello.c`:

```c
#include <stdio.h>

int main(void) { printf("Hello world!\n"); }
```

I use [lucet](https://github.com/bytecodealliance/lucet) to compile it:
`wasm32-wasi-clang hello.c -o hello.wasm` and run it successfully with `wasmer run hello.wasm`.
Then, I use the following pass: `wasm-opt hello.wasm --instrument-memory -o hello-inst.wasm` and then execution with wasmer fails:

```shell
$ wasmer run hello-inst.wasm
Error: Can't instantiate module: LinkError([ImportNotFound { namespace: "wasi_unstable", name: "fd_prestat_get" }, ImportNotFound { namespace: "wasi_unstable", name: "fd_prestat_dir_name" }, ImportNotFound { namespace: "wasi_unstable", name: "proc_exit" }, ImportNotFound { namespace: "wasi_unstable", name: "fd_fdstat_get" }, ImportNotFound { namespace: "wasi_unstable", name: "fd_close" }, ImportNotFound { namespace: "wasi_unstable", name: "fd_seek" }, ImportNotFound { namespace: "wasi_unstable", name: "fd_write" }, ImportNotFound { namespace: "env", name: "load_ptr" }, ImportNotFound { namespace: "env", name: "load_val_i32" }, ImportNotFound { namespace: "env", name: "load_val_i64" }, ImportNotFound { namespace: "env", name: "load_val_f32" }, ImportNotFound { namespace: "env", name: "load_val_f64" }, ImportNotFound { namespace: "env", name: "store_ptr" }, ImportNotFound { namespace: "env", name: "store_val_i32" }, ImportNotFound { namespace: "env", name: "store_val_i64" }, ImportNotFound { namespace: "env", name: "store_val_f32" }, ImportNotFound { namespace: "env", name: "store_val_f64" }])
```

Using binaryen built from current master.
Attachment: output files 
[instrument-memory.zip](https://github.com/WebAssembly/binaryen/files/4369778/instrument-memory.zip)

Any ideas?
Thank you

**Comment by kripken** [comment]
The missing `wasi_unstable` imports may be a current limitation in wasmer, best to ask them.

The missing `env` imports are because the instrumentation creates those imports and expects the runtime to support them. The nice thing about doing it that way is that it leaves the logging to the runtime - and not to code in "userspace" where you may be adding the logging to figure out a bug. For example, if we didn't go straight to the runtime and instead used `printf` for the logging, then the instrumentation pass would instrument `printf` itself! Which would be recursive and confusing.

Another option may be to run the instrumentation on a wasm file and then link in another wasm module that provides those imports. Not sure we have a good linker for that though (`wasm-merge` used to do it, but was removed; otherwise there is `wasm-ld` but it only links object files, and binaryen doesn't operate on those, only normal wasm files).

**Comment by orestisfl** [comment]
Thank you for your help! I understand this is not a binaryen so I am closing this.
