### ISSUE TITLE
Windows binaries are way bigger when built with github actions

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#2825]
See https://github.com/WebAssembly/binaryen/commit/8e017e9fe58687251275d6fe8a1a0b23813c3b1e#commitcomment-38898253

I guess we must be somehow build debug builds where we were not before.. but it certainly looks like we are building release.. so we need to investigate.

**Comment by schellingb** [comment]
At least binaryen-version_93-x86_64-windows.tar.gz is certainly a debug build. It contains .PDB and .ILK files and the executable depends on Visual Studio debug files (msvcp140d.dll, vcruntime140d.dll, vcruntime140_1d.dll, ucrtbased.dll). It also runs very slow compared to 92.
I have not investigated the linux or macos build but they also became significantly larger since 92.

OS | v92 wasm-opt | v92 all | v93 wasm-opt | v93 all
---|-----------------|---------|---------------|---------
win | 3 461 632 | 36 800 000 | 18 117 632 | 2 702 066 480
linux | 7 027 520 | 67 612 672 | 16 982 584 | 166 113 328
macos | 9 345 200 | 89 198 740 | 17 115 192 | 165 092 380

**Comment by sbc100** [comment]
The release build logs are here: https://github.com/WebAssembly/binaryen/actions/runs/90715136

From the cmake phase I see the follow on all three builder:  `-- No build type selected, default to Release`.. so I'm a little confused.    We probably need to add a cmake arg.. and compare with how we were building in the past on appveyor/travis.
