### ISSUE TITLE
LLVM issues with LTO-style static linking

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#292]
LLVM kind of dislikes LTO-style linking, by which I mean:
1. Application does not use libc memset
2. The LLVM memset intrinsic is used
3. We want to do fully static linking (LTO style) so we get rid of things that don't seem to be used (internalize all the things, then dce it all from orbit), and libc memset is not used, so it goes away
4. Codegen transforms the memset intrinsic into a libc call
5. :(

In asm.js, we work around this since we link in asm.js code _after_ (4), and for every LLVM intrinsic we have either a hand-written optimized asm.js version (e.g. memset), or an asm.js builtin (e.g. sin). For wasm, both can break.

Possible options:
- Take into account LLVM intrinsics in stage 3. This is tricky because (a) current LLVM tools don't let you (llvm-nm), we'd need to add something, and (b) it doesn't fully solve the problem since LTO optimizations [might invent a memset afterwards](https://llvm.org/bugs/show_bug.cgi?id=23814) (which is basically the same type of problem as 1-5 above).
- Always link in code for all LLVM intrisics (sin, cos, tan, memset, memcpy, memmove, etc. etc.), at the cost of code size.
- Do the same type of thing we did in asm.js

Thoughts?

cc @dschuff @jfbastien @sunfishcode

**Comment by dschuff** [comment]
It's actually even worse; IIRC according to the C standard the backend is allowed to generate calls to at least `memcpy`, `memset`, and `memmove` even if the intrinsics are not in the bitcode.

For PNaCl we have a 2nd (native) linking stage after LTO and codegen to satisfy memcpy/memset/memmove. (For the math functions, I think we have a separate bitcode library? I forget, I'll have to look). Medium/longer term for wasm, I'd like to have a non-LTO/bitcode linking mode as well, that can serve the same purpose. It can include compiler-rt (and libc/libm or some subset as well; "normal" LTO doesn't include libc itself, and therefore doesn't have the same issues we do). Longer term there's also of course dynamic linking.

In the short term, I actually wrote an LLVM pass to force memcpy, memset, and memmove to stay in the binary using LLVM's `llvm.used` mechanism for wasm. Then when I tested it out on emscripten's output I discovered it didn't do anything because those functions were not in the binary in the first place (as you noted, they are in Javascript), so I didn't land the change. But I can do that; we probably do want these in the wasm binary instead of in JS.

**Comment by kripken** [comment]
Interesting, I didn't realize that about the standard.

For now, I temporarily made emscripten just pin the memset, memmove and memcpy methods. That still leaves the math functions as a problem, and it wastes some code size, but we can optimize later (and it sounds like a valid thing to do in terms of the C standard).

The good news is that with that, and the last emscripten update (which has some other wasm backend fixes), I now see "hello world" working, using the wasm backend + emscripten + full musl! Next I'll start some larger programs in the test suite.

**Comment by tlively** [comment]
This is solved in Emscripten.
