### ISSUE TITLE
Don't require Python in build (if not found, skip those targets)

### ISSUE THREAD

**Issue by aardappel** [WebAssembly/binaryen#3036]
This is entirely similar to https://github.com/WebAssembly/wabt/issues/1385

On my Windows machine, CMake fails with:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PythonInterp: Found unsuitable version "2.7.15", but
  required is at least "3.5" (found C:/Python27/python.exe)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:391 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/passes/CMakeLists.txt:2 (find_package)
```

I have both Python2 and Python3 installed. The latter apparently needs to be invoked with `py -3`.

But more importantly, one should be able to build a C++/CMake project without needing Python at all. If it is used for tests, then it simply won't be able to run those tests if the user has no Python installed.

**Comment by aardappel** [comment]
De-installing Python 2 (hope nothing relies on it anymore) fixes it.. still should work without Python I think.

**Comment by kripken** [comment]
I believe we use python for two things. One is to autogenerate code for the parser, but we don't do that during build (the output is checked in). The other is `WasmIntrinsics.cpp` in `src/passes` has a script to embed code into it. Perhaps there is a better way?

https://github.com/WebAssembly/binaryen/blob/master/src/passes/CMakeLists.txt#L6

**Comment by MaulingMonkey** [comment]
```
CMake Error at C:/.../Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3.5" (found %LOCALAPPDATA%/Microsoft/WindowsApps/python3.exe)
```

This specific variation for version "1.4" can be encountered even if you have Python 3 installed earlier in your `%PATH%`, thanks to a "helpful" windows feature where `python.exe` and `python3.exe` "App Installer" stubs are added to your PATH:

```
python3.exe --version
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from
Settings > Manage App Execution Aliases.
```

Workarounds include:
* Running `python3` without args once first in a regular cmd.exe window? (untested)
* Unchecking the app installers under `Settings` > `Manage App Execution Aliases` (works for me)

**Comment by phated** [comment]
I've been doing some research around this because we'd like to drop the python dependency for Grain and I was wondering if it'd be satisfactory to implement it similar to https://github.com/ppaalanen/wesgr/commit/02a840cb7db7eeb80071a353f66865d729738ae5 (which I found through this StackOverflow: https://stackoverflow.com/questions/19638557/read-a-file-into-a-string-at-compile-time)

**Comment by phated** [comment]
This also might be possible through CMake's `configure_file` 🤔

**Comment by kripken** [comment]
`configure_file` might be a good option, first I heard of it though so I'm not sure.

Otherwise, we can do the same with WasmIntrinsics as we do with the parser, that is, one must call python manually to build the contents, which are then checked in as a C++ file, and the build system is unaware of the origin of that file.
