### ISSUE TITLE
Optionally use binary format in the various tools

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#304]
For example, asm2wasm should be able to emit either text or binary. This could make builds a lot faster for people not using text.

What kind of convention should we use? I think llvm tools have `-s` or something like that for text, and default to binary? Not sure if they autodetect based on the output suffix, if an output file is provided. Seems easier to not do that.

**Comment by dschuff** [comment]
asm2wasm is something we expect to be invoked by the compiler driver rather than directly by the user, right? So it probably doesn't make a huge difference. Even llvm tools are not consistent on this. `llc` defaults to text and has a `-filetype=<asm|obj>` flag. `opt` defaults to binary and has has `-S` for text. That would make sense for asm2wasm too I think.

Eventually when the binary format is stabilized we'll want binary output from emscripten by default. But in the near term (where binary formats for V8 may not exactly match SM or Binaryen) I expect for testing that I will want a wast output from emscripten, which I would translate with sexpr-wasm (which I do expect to be kept in lockstep with V8). So we have a bit of weirdness with emscripten, where you'll say you want `.js` output, but you also get a wasm (or wast) file too. And you can't just use `-S` with emscripten because for compiler drivers that means you want to stop before linking (i.e. it implies `-c`). 
So I might want to say that for now we should leave wast the default, but later (once users can expect to just build something and have it work in all wasm-supporting browsers) make binary the default.

**Comment by kripken** [comment]
Good points. However, using `asm2wasm` and then `wasm-as` is a lot slower than just `asm2wasm` that emits binary directly. For unity-size codebases, that can be significant, I measured and asm2wasm is around 10-15% of build time. It could be much less with just binary.

As for emcc knowing when to emit binary, we have `BINARYEN_METHOD` (see [docs](https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods), and if the user says there "I want a binary, and to interpret it", then we can tell `asm2wasm` to get straight to binary, etc.

**Comment by dschuff** [comment]
Oh, I forgot that the method could specify that. I guess we still have the interesting case that as far as I can tell, the native-wasm method generates a wast (which can then be passed to spidermonkify, right?). Maybe for the native case that's what we want (to get around binary format skew). We can make spidermonkify and sexpr-wasm have a common interface suitable for that purpose and pass either one to emcc.

**Comment by dschuff** [comment]
Or, I guess what you are trying to do is get rid of spidermonkify and use asm2wasm's output instead? Maybe we could just have a `native-wasm` binaryen method, and `native-wast`, or `native-binary` vs `native-s-expr` or something corresponding to the `interpret` cases.

**Comment by kripken** [comment]
native-wasm generating a wast is wrong, yeah. The reason it's like that is binaryen doesn't emit a binary that an engine can read. Once engines go postorder, that should change. And then we can make it emit a binary for native-wasm. And yes we'd get rid of spidermonkify.py at that time too (and other hacks if any).

**Comment by dschuff** [comment]
Right, but even once the engines go postorder, I wouldn't expect that e.g. V8 and SM will land the switch to a particular format milestone on the same day. So for me for testing, I would still want a method that behaves just as native-wasm does today... i.e. the Module glue is set up for native wasm, but there's a wast file I can encode with an external tool.

**Comment by kripken** [comment]
Yeah, we should keep the option to use the BINARYEN_SCRIPTS hook to run an external tool to emit binary.

**Comment by kripken** [comment]
This is a duplicate of #608.
