### ISSUE TITLE
Implement SIMD qfma/qfms in interpreter

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#3203]
`wasm-interpreter.h` has this:

```cpp
  Flow visitSIMDTernary(SIMDTernary* curr) {
      // [..]
      default:
        // TODO: implement qfma/qfms
        WASM_UNREACHABLE("not implemented");
    }
  }
```

Filing an issue for this TODO so we can track it in other issues.

**Comment by MaxGraey** [comment]
If nobody mind I could try to implement this

**Comment by tlively** [comment]
I don't think this is worth doing right now. The reason qfma/qfms are not going to be included in the first SIMD spec is because they are nondeterministic across platforms. Given that we haven't figured out how to spec that nondeterminism, we don't know what properties Binaryen is going to be expected to preserve when evaluating these instructions.

**Comment by MaxGraey** [comment]
I thought it should behave the same as NaN in spec. Basically, the behaviour of NaN is non-deterministic, but becomes deterministic when all arguments are constants and spec describe conversions for propagate two kind of NaNs in binary expressions for example. We discussed this recently. As for qfma / qfms within the interpreter, I think we should always use the "exact" (soft-float) version of `fma`. Or am I missing something?

**Comment by tlively** [comment]
Using a hardware independent implementation seems reasonable, but maybe we will end up specifying it so that the same precision is used for all fma operations in a single module or something like that, in which case Binaryen would need to match the behavior of the target machine to properly preserve semantics. We won't know until we have more spec discussions, so I don't think it is useful to implement anything right now.

**Comment by MaxGraey** [comment]
Ok, will wait spec stabilization then

**Comment by kripken** [comment]
This has been fixed.
