### ISSUE TITLE
Windows (VS2013) doesn't compile

### ISSUE THREAD

**Issue by griffin2000** [WebAssembly/binaryen#325]
Windows doesn't compile for me, had to hack file.cpp a bit to get it to work.

[file.zip](https://github.com/WebAssembly/binaryen/files/209694/file.zip)

**Comment by jfbastien** [comment]
Please send a PR.

**Comment by griffin2000** [comment]
PR sent. Thought note this just is just code that works for me, not necessarily suitable for checking into master.

**Comment by jasonmoore29** [comment]
I also cannot compile using VS2015, after following the instructions on https://github.com/brakmic/brakmic/blob/master/webassembly/COMPILING_WIN32.md 

The issue is also in file.cpp
`
Error	C2676	binary '|=': 'std::_Iosb<int>::_Openmode' does not define this operator or a conversion to a type acceptable to the predefined operator	support	binaryen\src\support\file.cpp	27	
Error	C1001	An internal error has occurred in the compiler.	support	binaryen\src\support\file.cpp	27	
`

**Comment by kripken** [comment]
This is definitely an area where we need help! Most (all?) of the main devs here are not on windows, and the VS errors are very unclear sometimes, at least to me. The current errors can be seen on the [emscripten windows bot](http://clb.demon.fi:8112/waterfall), btw (search for "test_binaryen"), e.g. [here](http://clb.demon.fi:8112/builders/win-incoming/builds/1232/steps/Tests-default/logs/stdio)

**Comment by griffin2000** [comment]
That is the same error I got in VS2013, I fixed by making everything an int, but I suspect that is not the correct solution. I will see if I can work out the correct fix when I get the chance (if no one else gets to it first)
