### ISSUE TITLE
Switch Names to be indices

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#336]
Right now Names are interned strings. This has been useful for debugging as we build the compiler up (dumping legible ASTs is possible from anywhere), but at this point things are fairly stable. So we could consider moving Names to just contain a `uint32_t` index. Benefits:
1. As mentioned [here](https://github.com/WebAssembly/binaryen/pull/328#issuecomment-208561479), people emitting wasm ASTs might not want to bother with naming all locals, etc.
2. Performance. Although, the strings are interned, so they are just pointers, so I don't expect a big speedup. But in some cases we use a name as a hashtable key, which could become an array lookup.

We would need to move names to side metadata in the Module. This would be the first time that a node has part of it's data on the Module; up to now, you could transplant ASTs from Module to Module. I'm not worried about losing that, but one issue to be aware of is that this adds global Module state, which means it has to be threadsafe for passes to be function-parallel, which we definitely want and is easy to do.

**Comment by dschuff** [comment]
Comment copied from the other discussion:
Probably the IR should reflect the AST semantics, which is that the index is the canonical identifier, but locals can optionally have names as well. E.g. maybe the IR node for a function has a list of names of locals, any of which can be empty. Names only get updated on function creation. The IR node for get_local just has an index. And maybe there are 2 builder methods for get_local, which take an index or a name. Or something like that.

**Comment by dschuff** [comment]
(also the state would then be local to a function, rather than global to the module)

**Comment by kripken** [comment]
I like the idea of names being on functions, it solves the parallelism issue. But not sure about how printing nodes would work: if the name info would be on the function, then to print a node, we must know its function. I really hope we can avoid each node having a parent pointer (like e.g. LLVM has). For the module, on the other hand, I was thinking it would be known globally anyhow, as when running functions in parallel they all use the same module. But, I haven't thought this through fully, I'd need to write some code to do that I guess.

**Comment by kripken** [comment]
Ok, after more though, I do think we can put local names on functions, and turn local names into indices with optional string names.

I was also thinking we could do the same for other names, like block and br names, but realized that would be bad for compositionality (i.e. adding another block would require changing indices all around). But I think it's fine, the vast majority of names used currently are local names, and we have a plan for that.

**Comment by dschuff** [comment]
Aren't there are a lot of the same problems for locals as for block names?
To add a local, you can just append to the end of the list. But if you remove one from the middle, what do you do? Probably you'd just leave it there as a tombstone.

Instead of names or indices you could just make IR data structures for everything, including locals, blocks, etc. (the IR structure would optionally have a name). Then nothing would have an index at all until you wrote it out. Then all IR nodes that refer to other nodes (get_local, br) would just use pointers instead of indices. That might cost more memory than you'd want to pay. 

Maybe best would be just to do both. Everything except locals already has an IR node anyway, right? so pointers to those IR nodes are the way they are represented in the in-memory AST. Then when you write it out you assign indices, break depth, etc. For locals, you could keep using indices and if you deleted one, just leave a sentinel value and re-number before you print or as you go.

**Comment by kripken** [comment]
Yeah, for adding names you can just append. To remove, you can just not use a local, then run the pass the reorders by frequency, which drops unused ones. Whereas for blocks, you'd be in a literally incorrect state for a while. More generally, I think we can consider blocks are part of the AST, and the indexes depend on the AST, while local names do not, they are just a list on the side basically. So indices for locals seems to make sense to me, but not for labels and so forth.

About memory, yes, I think it would best to avoid unnecessary IR nodes, and to reduce the size of existing nodes. I think after this change, we'd be pretty good, as it would reduce set_local and get_local blocks in size by replacing a pointer with a 32-bit offset, and those are the most common nodes. And our other IR nodes are fairly compact already (barring obvious stuff we need to optimize, like we still use std::vector in blocks).

**Comment by kripken** [comment]
This was implemented by that PR, but we forgot to close this.
