### ISSUE TITLE
Disable optimizations when using wasm EH even when O2 is specified

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/binaryen#3586]
Currently Binaryen is able to parse EH-using wasm binaries (which means that emscripten can work end-to-end when using `-O0` or `-O1` and `-s WASM_BIGINT` with `em++`and no features that require transformations). But it will take a bunch more work to get all the analysis and optimization passes working and stable with EH.
I think we should make it such that emscripten will work correctly end-to-end even when using higher optimization levels with `em++`. One way to do this would be to make `wasm-opt -O2` avoid trying to do unsupported optimizations when wasm EH is used (then the compiler driver and emscripten users wouldn't have to do anything special, and we could enable the optimizations in Binaryen whenever they work).
The other option would be to put special logic in the emscripten driver to avoid ever invoking wasm-opt or finalize with unsupported optimizations. Given that what's supported may change in Binaryen, it seems like it might be simpler to do the disabling there, but I don't have a strong opinion on that.
Thoughts on the best way to do this?

/cc @aheejin  @kripken @tlively

**Comment by dschuff** [comment]
I guess we'd also have to make `wasm-metadce` do the right thing too? Maybe nothing special would have to be done there if it's just eliminating a whole function at a time?

**Comment by aheejin** [comment]
Possible alternatives:

1. In Binaryen, if 'exception-handling' feature is enabled, force -O2 or above to -O1.
This is risky because all users who just want to enable all features using `-all` will not be able to use optimizations.

2. In Binaryen, if there are actually EH instructions in a function, force -O2 or above to -O1.
This can be less risky, but it needs scanning the function or module beforehand, so it looks not very cleaner to me.

3. In Emscripten, if `-fwasm-exceptions` is used, give `wasm-opt` `-O1` when `-O2` or above is given in the command line.
I think this is the best option among these three, but maybe there can be other options I haven't thought about.

**Comment by tlively** [comment]
Another possibility would be to do this on a per-pass level rather than via optimization levels. A similar mechanism already exists for skipping passes that would invalidate DWARF. We could have passes implement a `supportsEH` function in addition to the current `invalidatesDWARF` function.

**Comment by kripken** [comment]
I guess the question is how long do we expect to need to work around this? If it's not long then maybe we don't need a temporary mechanism here.

I hope it won't take that much work actually. I've been fuzzing `wasm-opt` roundtripping and kind of by mistake I ended up fuzzing `-O1` as well (because it made the testcases smaller). With the open PRs all applied I can run the fuzzer for thousands of iterations on `-O1` (both LLVM and Binaryen) with no issues. There are some additional passes that run in binaryen `-O2+`, but not many, so I'm hopeful.

But if we want to be more safe, I'd prefer @aheejin 's option 3 (plus a warning).

**Comment by aheejin** [comment]
@tlively
The tricky thing is we don't precisely know which pass supports EH and which does not, because we just haven't tested them enough. So to be conservative we maybe have to put `supportEH() = false` for all existing passes now, which I think is too much?

@kripken 
I'm mostly worried about `delegate` and its control flow ramifications on the existing analyses and passes. Also it's gonna take a while to fuzz all passes to make sure. Yeah I don't want to do this either but apparently I'm being asked for the schedule every few days so.

**Comment by dschuff** [comment]
Given that we'd like to have a toolchain testable by end-to-end by non-emscripten-developers as soon as we can (and that we are targeting LLVM first), I think it makes sense to have this kind of mechanism temporarily, especially if it's not overly complicated. 
Based on what @aheejin said above, I agree that option 3 makes the most sense. I don't know that I'd want a warning though. It wouldn't really be actionable and would trigger on basically every link, right?

**Comment by kripken** [comment]
Good points. Ok, option 3 seems best to me, and better than doing nothing.

I think a warning might be less surprising, but given this is an experimental feature, I guess it's fine without. Although another factor is people might link with `-fwasm-exceptions` and see the code size is larger than `-fexceptions`. Maybe a general warning on wasm exceptions might avoid confusion there. But I don't feel strongly.

@dschuff  Aside from optimization levels, we may have issues with flatten which affects asyncify for example? Not sure - @aheejin ? We can maybe just error in emcc on those modes for now.

**Comment by aheejin** [comment]
@kripken Are there any passes that don't support Asyncify? You mentioned Asyncify and I'm not sure how that's related to this issue, so...

I'm also OK with explicitly error out when user gives `emcc -fwasm-exceptions -O2 (or above)` with an error message that wasm EH is an experimental feature and does not support -O2 or above yet. That might be less confusing, if there's a way to disable certain optimization flags in test_core.py per tests. @dschuff seemed to think we should not error out on any opt levels though. Do you have a particular reason on that?

**Comment by kripken** [comment]
@aheejin Sorry, I meant that Flatten (required for Asyncify) might not be compatible with EH. Testing now I see it errors if it encounters a Try. That seems good, no risk of confusion there, until we fix it (which I don't think it urgent).

**Comment by dschuff** [comment]
Mostly my thought was that if we just limited the `wasm-opt` optimizations, then O2 and above at link time could still use the other things that emscripten does at that level, e.g. JS optimizations. So it could still be better than O1 even without `wasm-opt`. But maybe that's not a huge advantage, since O2 and above can still be used at compile time. so I don't feel too strongly about it.
