### ISSUE TITLE
Invalid optimization, ignoring side effect on field value

### ISSUE THREAD

**Issue by askeksa-google** [WebAssembly/binaryen#3655]
With `-O1` or higher, Binaryen turns this:
```wat
(module
 (type $A (struct (field (mut i32)) (field (mut (ref null $B)))))
 (type $B (struct (field (mut i32)) (field (mut (ref null $C))) (field (mut (ref null $B)))))
 (type $C (struct (field (mut i32)) (field (mut i64))))
 (export "f" (func $f))
 (func $f (param $0 (ref null $A)) (result (ref null $C))
  (local $1 (ref null $C))
  (local.set $1
   (struct.get $B 1
    (struct.get $A 1
     (local.get $0)
    )
   )
  )
  (struct.set $A 1
   (local.get $0)
   (struct.get $B 2
    (struct.get $A 1
     (local.get $0)
    )
   )
  )
  (local.get $1)
 )
)
```
into this:
```wat
(module
 (type $B (struct (field (mut i32)) (field (mut (ref null $C))) (field (mut (ref null $B)))))
 (type $A (struct (field (mut i32)) (field (mut (ref null $B)))))
 (type $C (struct (field (mut i32)) (field (mut i64))))
 (type $ref?|$A|_=>_ref?|$C| (func (param (ref null $A)) (result (ref null $C))))
 (export "f" (func $f))
 (func $f (; has Stack IR ;) (param $0 (ref null $A)) (result (ref null $C))
  (struct.set $A 1
   (local.get $0)
   (struct.get $B 2
    (struct.get $A 1
     (local.get $0)
    )
   )
  )
  (struct.get $B 1
   (struct.get $A 1
    (local.get $0)
   )
  )
 )
)
```
Essentially, it is replacing
```
c = a.b.c
a.b = a.b.b
return c
```
by
```
a.b = a.b.b
return a.b.c
```

**Comment by kripken** [comment]
I believe this is because Binaryen is willing to reorder two operations that can trap. In this example the two instructions even have the same trap type, but Binaryen would also reorder different traps. The idea is that we do not remove a trap, but if a problem is going to trap anyhow, then we do not care about precisely preserving the trap or the code path to it.

(If the operation in the middle were something like a call, that has additional non-trap side effects, it would not reorder it.)

Is this a concern for your codebase - do you care about trap differences or reorderings?

**Comment by askeksa-google** [comment]
It's not about trapping. Binaryen reorders a read and a write to the same field (`a.b` in the example), which changes the behavior of the program.

As for my codebase, the transformation turned a working program (without traps) into a broken one (dereferencing a null reference, but this in incidental - it could just as well have acquired a different non-trapping behavior).

So no, I don't particularly care about trap reorderings (or turning implicit traps into undefined behavior), but I do care about preserving the semantics of non-trapping code. 😉

**Comment by tlively** [comment]
I'm fixing this now.

**Comment by kripken** [comment]
Thanks @tlively ! And yes, sorry for misunderstanding before @askeksa-google , I missed that there was a write to memory in there...
