### ISSUE TITLE
Parse exception for valid heap type

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/binaryen#3656]
Hello,
I am trying to parse a .wasm file and I am getting the following message:
`[parse exception: invalid wasm heap type: -64]`
I believe this might be a large positive heap index which does not fit in one byte and is encoded as a LEB128 in multiple bytes, as required by spec: https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#heap-types-2.

**Comment by kripken** [comment]
We use an S64LEB atm there,

https://github.com/WebAssembly/binaryen/blob/dfafe354a0ebb6250851399a36b8263dd3d43de3/src/wasm/wasm-binary.cpp#L1628-L1644

I think that is technically inaccurate as it should be S33, but there should be no noticeable difference aside from allowing higher (very unlikely) numbers. So this should be handling multi-byte indexes already, and I'm not sure what is wrong.

I also tested with a file with 5,000 heap types, using the below script, and I don't see an error. Binaryen can read the binaries it writes, and wasp can read them as well.

```py

print('(module')

TYPES = ['i32', 'i64', 'f32', 'f64', 'funcref', 'i31ref', 'externref', '(ref null 0)', '(ref null 1)']

i = 0

MAX = 5000

for a in TYPES:
  for b in TYPES:
    for c in TYPES:
      for d in TYPES:
        if i >= MAX:
          break
        fields = ['(field %s)' % t for t in (a, b, c, d)]
        print(' (type $struct%d (struct ' % i, ' '.join(fields), '))')
        i += 1

for a in range(i):
  print(' (func $func%d (param (ref null $struct%d)))' % (a, a))

print(')')
```

Is there a chance that wasm file is invalid?

**Comment by manoskouk** [comment]
Looking up `getHeapType` I found this function:

https://github.com/WebAssembly/binaryen/blob/101aac786ccffe3714fdcf05437b2b740135b4de/src/wasm-builder.h#L914-L922

However, [rtts](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#reference-types-1) do not take heap types as inputs anymore, but rather type indices.

Maybe that could be at fault?

**Comment by kripken** [comment]
Hmm, I'm not sure that is a problem. First, that code is for the IR itself, that's not binary reading or writing code. But, the binary reading code does write a heap type, that is true:

https://github.com/WebAssembly/binaryen/blob/101aac786ccffe3714fdcf05437b2b740135b4de/src/wasm/wasm-binary.cpp#L1088-L1098

However, I think that is correct? A non-negative heap type is a type index. So the difference, as I understand it, between a type index and a heap type is that a heap type can also be something like `funcref` (which is negative). So the change from a heap type to a type index rules out `(rtt funcref)` but otherwise left the binary format unchanged, I think? Maybe I'm missing a subtle encoding difference however.

To check myself I added rtts to that python script,
```python

print('(module')

TYPES = ['i32', 'i64', 'f32', 'f64', 'funcref', 'i31ref', 'externref', '(ref null 0)', '(ref null 1)']

i = 0

MAX = 5000

for a in TYPES:
  for b in TYPES:
    for c in TYPES:
      for d in TYPES:
        if i >= MAX:
          break
        fields = ['(field %s)' % t for t in (a, b, c, d)]
        fields += ['(field (rtt $struct%d))' % i]
        print(' (type $struct%d (struct ' % i, ' '.join(fields), '))')
        i += 1

for a in range(i):
  print('''\
 (func $func%d (param (ref null $struct%d))
  (drop (rtt.canon $struct%d))
 )
''' % (a, a, a))

print(')')
```
It now emits things like this:
```wat
 (type $struct0 (struct  (field i32) (field i32) (field i32) (field i32) (field (rtt $struct0)) ))
..
 (func $func0 (param (ref null $struct0))
  (drop (rtt.canon $struct0))
 )
```
And I verified that the latest v8 from jsvu can read binaryen's binary output for that properly, https://storage.googleapis.com/chromium-v8/official/canary/v8-linux64-rel-9.1.67.zip

(If you can provide the wasm file you are seeing the problem on I'd be happy to take a look at it.)

**Comment by kripken** [comment]
Oh, I think I was wrong here. Testing a change to write a U32LEB I do see a change in the binary format. Looks like the encoding of the highest bit can differ even though all U32 values fit in S64s, as in the shortened encoding we may need to add another byte depending on the sign.

And I guess that jsvu version is too old, and V8 has been updated to the new format only after that release (9.1.67)? I'll build from source to verify.

So it looks like wherever there is a typeindex Binaryen needs to write a U32LEB instead of an S64LEB that happens to be positive. If that sounds correct to people I'll work on a patch.

**Comment by kripken** [comment]
Actually V8 `1a4c5211c1f529f8be654f7092952d988a5f689a` does not error on either modes. So perhaps the testcase here is not sensitive enough to show an actual problem. But I do think this needs to be changed - please confirm.

**Comment by manoskouk** [comment]
I think you might even interpret a one-byte type wrong if you choose signed over unsigned interpretation. Example: If you read the byte `0b01000000` as an S64LEB, you will interpret it as -32, which is an invalid type, whereas if you read it as a U32LEB you will interpret it as 32, which might be a valid type.

**Comment by kripken** [comment]
The testcase here seems to not work yet.

**Comment by kripken** [comment]
@manoskouk 

Oh, and yes, good point, it could be invalid that way. I didn't notice it because all the types in the artificial testcase happen to be compatible with each other.
