### ISSUE TITLE
[Wasm GC][wasm-dis] Type index should be printed over type description for reference types

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/binaryen#3713]
As an example, I am getting this from wasm-dis for a parameter definition:
`(param $0 (ref null ${mut:i32_mut:ref?|...0|_mut:i64_mut:i64_mut:i64_mut:ref?|[mut:i64]|}))`

**Comment by kripken** [comment]
I think this will be fixed by @tlively 's work on replacing these names with better ones, https://github.com/WebAssembly/binaryen/issues/3627

I'm not sure I understand the bug, though. Is the issue that the `...` has skipped some part of the name, and so you can end up with duplicate names? If so this is https://github.com/WebAssembly/binaryen/issues/3687

**Comment by manoskouk** [comment]
Sorry for not being clear. In my opinion, only the index of the type should be displayed. In any case this is a duplicate, and I will continue discussing at #3627. Thanks!
