### ISSUE TITLE
`BinaryenExpressionCopy()` does not rename blocks

### ISSUE THREAD

**Issue by ImmanuelHaffner** [WebAssembly/binaryen#3762]
The function `BinaryenExpressionCopy()` of the Binaryen C API creates a deep copy of an expression.  Any blocks inside this expression are copied with their exact name.  This, however, violates the constraint that *«names in Binaryen IR must be unique - IR generators must ensure that»*.

Should `BinaryenExpressionCopy()` rename the blocks while creating a deep copy?  If no, what is the correct approach to copy expressions containing blocks? Is this actually supported?

**Comment by kripken** [comment]
This is a potential problem, yes. But note that `BinaryenExpressionCopy()` can't rename them itself because it depends where you are copying them to. If it's to the same function then it definitely needs to rename them, but it would need to see all the rest of the function to know what are valid names (there could be possible collisions with potential new names). And if it is copied into another function (perhaps an entire function body is copied to create a new one) then no renaming is needed. So by default it does not rename.

There is an internal utility for this, `UniqueNameMapper::uniquify` which could be added to the C API. I think that would solve this.

**Comment by ImmanuelHaffner** [comment]
Ah, good catch! Does `UniqueNameMapper::uniquify` also change block/loop names and branch targets?  If so, adding a flag to `BinaryenExpressionCopy()` or providing something in the likes of `BinaryenExpressionCopyUnique()` could do.

**Comment by ImmanuelHaffner** [comment]
For now, I changed codegen to circumvent copying the expression with a loop.

**Comment by kripken** [comment]
Yes, `uniquify` changes block/loop names and the breaks to them.

`BinaryenExpressionCopyUnique` is one possibility. But it would need not just the code to copy, but to be passed the function to copy it in (to find potential collisions). Something like `BinaryenExpressionUniquify` may be more generally useful, as ensuring uniques names may matter not just after copying, although I agree copying might be the most common case.
