### ISSUE TITLE
How to identify the dynamic linking table?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#3823]
module-splitting.cpp currently runs this code when it adds a new item to the "active table" to update the dylink section to account for the new table size. 

```C++
  addSlot(entry->func, newSlot);
  if (activeTable->initial <= newSlot.index) {
    activeTable->initial = newSlot.index + 1;
    if (module.dylinkSection) {
      module.dylinkSection->tableSize = activeTable->initial;
    }
  }
```

This is correct if `activeTable` is the table used for dynamic linking, but in general `activeTable` may be some arbitrary other table that the dynamic linking ABI knows nothing about. In that case, how can we tell whether or not this table is the one referred to by the dylink section? If there is a dylink section, are we guaranteed that there exists a table and that the table at index zero is the one used in dynamic linking?

cc @sbc100

**Comment by sbc100** [comment]
Any wasm module produced by llvm today will have (at most) a single table and (at most) a single memory.   Modules that have more than one table or more than one memory are currently not supported (that I know of) by any elements of the emscripten toolchain, from llvm, to binaryen to emscripten's python driver code.    We have plans add support for such things but its safe to assume that today we only deal with single-memory and single-table modules.  At least, that is my understanding.

The good news is that we at least have a name for the single table which is `__indirect_function_table`.   The table size and alignment refereed to in the dylink section refer specifically the elements that a module required in this table.  This information exists so that a dynamic linker (such as emscripten) can allocate the needed amount of space in `__indirect_function_table` prior to loading a given module.  The same goes for `mem_size` and `mem_align`.    Clearly the dylink section would need to be expanded upon or replaced in the presence of multi-table and/or multi memory.

**Comment by tlively** [comment]
This isn't urgent, but I'm thinking about the near future when we have multiple tables in LLVM output or modules from other producers. Binaryen already support multiple tables thanks to the great recent work from @martianboy, too.

I just checked and it looks like the `__indirect_function_table` name is picked up by Binaryen as the internal name of the table at least in a simple example, so that could be a reasonable way to solve this problem. Are there any cases in which the `__indirect_function_table` name is not present in the output?

**Comment by sbc100** [comment]
Yes, `__indirect_function_table` should always exist, either as an import or an export.
