### ISSUE TITLE
[wasm-split] using multiple profiles at once

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#3912]
Right now wasm-split's instrumentation produces one profile per run and the splitting logic consumes one profile. That means that it only natively supports splitting based on a single workload. In practice, it is more useful to be able to run multiple workloads and use them all to inform splitting.

I was thinking that the simplest solution would be to allow profiles to be concatenated to each other to form a larger file and to have wasm-split accept and use such concatenated profiles.

An alternative solution that would keep profile files smaller would be to add an option to wasm-split to combine two (or multiple) profiles into a single profile. This would be more complicated because it would require wasm-split to do more things, but it wouldn't need separate user-provided concatenation logic.

Any thoughts about what would be the best design and semantics here?

cc @sbc100, @awtcode, @sps-gold, @Mintyboi, @waterlike86

**Comment by sps-gold** [comment]
I think rather than concatenating profiles into large file, it will be better to merge all profile data into one table. This will keep output profile file size constant, and we not loose any info because all we need during split is just to know if the function should belong to main or deferred module.

I also prefer alternate solution as if we extend wasm-split to use for merging profiles, say like
`wasm-split --merge_profiles output_profile <list of input profiles>` and/or
`wasm-split --merge_profiles main_profile profile_to_merge`
then we can reuse existing read/write profile logic and no maintenance of separate code base be required. 

PS: It might also be good to log some information around merge. Like if profile_to_merge is a subset of main_profile in example above then we can drop the run for profile_to_merge as it does not contribute any extras.

**Comment by tlively** [comment]
This was implemented in #3917.
