### ISSUE TITLE
Unknown function addresses in s2wasm

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#392]
s2wasm accepts an unknown symbol, as it can later be added from JS - we just call out to it. Something we don't support yet though is taking the address of an unknown symbol. We should create a thunk to it, so that we can put the thunk in the function table.

**Comment by dschuff** [comment]
#554 and its counterpart in LLVM are a little bit of a hack. What we really want is a way to explicitly specify the list of functions (with their signatures) that are available for import, which would be available to the final linker at link time. Currently the linker just takes all the undefined functions and turns them into imports, but an import file would allow us to specify the available syscalls and other emscripten-provided imports, as well as allow users to plug in their own, and the signatures would come from the definition rather than the use of the imports.

**Comment by dschuff** [comment]
With LLVM r271599 this should be fixed.
