### ISSUE TITLE
wasm2js: incorrect translation of `atomics.notify`

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#4393]
It looks like the `count` argument to `atomic.notify` is not being adjusted correctly when converting to the JS call `Atomic.notify`.

The `count` argument of < 0 to the wasm function should be translated to `Infinity` in the JS call but instead is just passed through.

**Comment by conrad-watt** [comment]
I think passing the argument through is the conformant behaviour. A while ago, we changed `atomic.notify` to treat its `count` argument as unsigned, rather than using a negative signed argument as an infinity signal.

It looks like the Web embedding described by the [threads overview](https://github.com/WebAssembly/threads/blob/main/proposals/threads/Overview.md#notify) wasn't correctly updated to reflect this change (although the text above was). I'll fix the overview now.

**Comment by sbc100** [comment]
In on the web it looks like the double `Infinity` is used signal the waking of all threads:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/notify

```
count Optional
The number of sleeping agents to notify. Defaults to +Infinity.
```

Is there an equivalent for the wasm instruction?  Should we map MAX_INT in wasm to +Infinity. in JS?

**Comment by conrad-watt** [comment]
In Wasm, we assume there will never be more that `2^32 - 1` suspended threads (see the note for `wait` [here](https://github.com/WebAssembly/threads/blob/main/proposals/threads/Overview.md#wait)).

In the meeting where this decision was made, there was a general expectation that, in both Wasm and JS, implementation-specific limits on suspended threads would be hit long before this, and we agreed that we'd add a separate `notify_all` instruction if this expectation later proved to be incorrect (so that `notify` could continue to report the precise number of threads woken as an `i32` output).

It's probably harmless to map very large `count` arguments to `infinity`, but has a program been observed with `2^32 - 1` (or at least, `2^31`) suspended threads that would make this difference observable? If so, we probably do need to think about a `notify_all` instruction in Wasm.
