### ISSUE TITLE
Thread stack size of prebuilt binary for linux may not be enough

### ISSUE THREAD

**Issue by kateinoigakukun** [WebAssembly/binaryen#4401]
Hi, I'm using binaryen's Asyncify to port CRuby to WebAssembly.

I found that when using [prebuilt binary of binaryen 1.0.3](https://github.com/WebAssembly/binaryen/releases/download/version_103/binaryen-version_103-x86_64-linux.tar.gz), it exits with segmentation fault due to stack overflow with my binary on Linux. However, it succeed when using self-built binaryen and version 0.9.9's prebuilt binary.

Here is how to reproduce the seg fault.
```console
$ wasm-opt --asyncify -O3 --pass-arg=asyncify-ignore-imports -o miniruby.opt.wasm miniruby.wasm
```

[miniruby.wasm.zip](https://github.com/WebAssembly/binaryen/files/7732420/miniruby.wasm.zip)

After some investigations, I found that

-  the prebuilt binary links musl instead of glibc and musl's default thread stack size is much smaller than glibc's one: https://wiki.musl-libc.org/functional-differences-from-glibc.html
- a function in my binary nested too deeply https://gist.github.com/kateinoigakukun/fb8b9ddd98e96183694dde408d97e428, 
- Asyncify processes its transformation recursively: https://github.com/WebAssembly/binaryen/blob/80101484099e9451072eb8c10df69499031b3475/src/passes/Asyncify.cpp#L883

So, is it acceptable to extend the default thread size by adding `-Wl,-z,stack-size=N` for building prebuilt binaries?

**Comment by kripken** [comment]
Interesting...

I think it might be better to limit the recursion there. We could rewrite the `process(..)` calls to use a stack. Specifically though I am 99% sure that this is due to heavily nested blocks (that's the only real pattern in wasm where this is an issue), and so using a stack just in the code for blocks might be enough, which would be less work.

**Comment by kripken** [comment]
Side question, what part of CRuby needs asyncify? File operations? (just curious)

**Comment by kateinoigakukun** [comment]
@kripken OK, I'll try to rewrite the `process` method in a few days.

> Side question, what part of CRuby needs asyncify? File operations? (just curious)

CRuby uses Asyncify to implement setjmp and longjmp in userland for non-local exits, and also to support context-switching for Fiber.
c.f. https://github.com/kateinoigakukun/ruby/tree/e3b5c3c232f151bd4de4e6bf2d48790987a4ae96/wasm

**Comment by ko1** [comment]
and conservative GC

**Comment by kripken** [comment]
Interesting, thanks for the info @kateinoigakukun and @ko1 !

**Comment by Lynieya4040** [comment]
Omg 🥰that was non stop it's not intentional it unexplainable certainly will need to shields it's learning habit, there like hmm 🤭 babies best way I can't explain, I didn't use anything, they measurements of the now., then, and , present time, I'm very new to this ideas... It not that basic to kept installing un installing reinstated.... It's cause unseen behaviors, I can't predict these behaviors either, fact is that multiple task it creates, a kind of like tired 😴 
Out of engery, like examples, please be considered of certain task in projects perimeters, over excessive back to back construction 🚧📚✏️📌✂️⛏️⚒️📐✒️📘🖋️🖊️📎 it's has a impact on the environment suddenly change, it's instantly done ✅,"factors to remembering limiting how many projects link need be pointed out" we are human and the amount of the basic follow and clean fix, at time because I'm human, forget that what was the step the instructions information, I mean it's can tired 😴 a person out... I'll need to follow tomorrow it's almost 1.30 I been doing this for a good leangth of time my spelling is of too  
Aside from being sleepy i in joy the well detailed step to step ,📘✏️📐📎💻📌ℹ️📚💻✏️ information it's honestly help the process
