### ISSUE TITLE
finalize method of Block method is invalid

### ISSUE THREAD

**Issue by MI3Guy** [WebAssembly/binaryen#455]
It performs an assignment from a field to itself and ignores the parameter. As far as I can tell, this method is not used.

**Comment by kripken** [comment]
Thanks, yeah, that was a bug. Not noticed since it's indeed not used yet.

The idea though is that it's an optimization. If someone builds wasm and they know block types, they can avoid the scanning that the default finalize method does. So far nothing in the codebase tries to optimize that way.

Fixing in #457.
