### ISSUE TITLE
Static casts with structural types

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#4599]
Should this trap?
```wat
(module
 (type $A (struct (field i32)))
 (type $B (struct (field i32) (field i32)))
 (func "foo"
  (drop
   (ref.cast_static $A
    (struct.new $B
     (i32.const 1)
     (i32.const 2)
    )
   )
  )
 )
)
```
It traps with `--fuzz-exec-before -all`, that is, running the code with the default structural typing. This led to the fuzzer saying it is a bug in OptimizeInstructions which will remove that static cast since it looks like it must succeed. Shouldn't it succeed in structural subtyping @tlively ?

**Comment by tlively** [comment]
Trapping is correct behavior here because `cast_static` is sugar for an RTT cast with canonical RTTs and `struct.new` is sugar for `struct.new_rtt` with a canonical RTT. In the equirecursive type system, unlike in the other two type systems, canonical RTTs never encode any subtype relationship. To make this cast succeed as you expect, you would need to allocate the `$B` with `(rtt.sub $B (rtt.canon $A))` to make the `$B` RTT a sub-RTT of the canonical `$A` RTT.

... but of course none of that is relevant to how the current proposal works.

**Comment by kripken** [comment]
Ah, thanks, I forgot the sugar stuff with rtts...

Ok, as this is found by the fuzzer now, I guess we should fix it. Obvious options are either to disable that optimization in structural typing, or switch the fuzzer to nominal typing. I'll start to look into the latter which we need anyhow, but not sure how much work that would be.

**Comment by tlively** [comment]
Sounds like disabling this optimization under equirecursive typing would be most correct, but not as practically useful as switching the fuzzer to use nominal (or isorecursive!) types. I would be surprised if switching the fuzzer to use a different type system is a lot of work.

Taking a brief look now, it looks like fuzzing.h declares a `setupHeapTypes` method, but it is not defined or called anywhere :laughing: If you want to make the fuzzer more useful without depending so heavily on mutating recent tests, you could try initializing the heap types by calling the `HeapTypeGenerator` API in tools/fuzzing/heap-types.h. I never got around to integrating that into the main fuzzer.

**Comment by kripken** [comment]
Ok, after a few days work I think we are close to switching the fuzzer to nominal typing, so this issue is probably not worth fixing.
