### ISSUE TITLE
Parse exception - unexpected end of input

### ISSUE THREAD

**Issue by igoriakovlev** [WebAssembly/binaryen#4732]
Hi,

I got parse exception on some of my .wasm files (d8 runs this without an issue) for [main](https://github.com/WebAssembly/binaryen/commit/96923f19eb0e7233fd1c7f438d3ebcf97690fd53) 

The result I got is:
`[parse exception: unexpected end of input (at 0:1071307)]
Fatal: error parsing wasm`

Here you can find the .wasm:
https://drive.google.com/file/d/1Bh87RkAFnsSqurzxX0pf_2HKt5zAsCwz/view?usp=sharing

Minified line to reproduce:
wasm-opt --hybrid new-mpp-wasm-node-test-wasm-test.wasm -o /dev/null

Thank you.

**Comment by kripken** [comment]
The exception happens inside the name section. V8 will silently ignore invalid name sections, so it's possible that's what's happening here.

Looking more deeply, this is the GC NameField subsection in the name section. It declares 543 types, and the error happens on the start of the 535 one where the input ends prematurely. Type 534 looks valid, as the last field name emitted there is `suppressedExceptionsList`. So this doesn't look like an invalid length of a name or something else that leads to reading random bytes. The problem seems to be that the section claims to have 543 types but only contains 534.

Here is the binaryen code to read that section, if that helps:

https://github.com/WebAssembly/binaryen/blob/96923f19eb0e7233fd1c7f438d3ebcf97690fd53/src/wasm/wasm-binary.cpp#L3282-L3301

**Comment by igoriakovlev** [comment]
I will check it. Thank you!

**Comment by igoriakovlev** [comment]
Found the bug in Kotlin/Wasm emitter. Thank you!
