### ISSUE TITLE
Significant perfomance degradation for binaryened code

### ISSUE THREAD

**Issue by igoriakovlev** [WebAssembly/binaryen#4769]
Hi,

I see the significant degradation of code optimised with Binaryen (x6 times slower than original).

We now have some benchmarks for Kotlin/Wasm compiler and we are comparing optimised code with the original one.
The Kotlin code for one of these cases looks like this:
```
private const val RUNS = 1_000_000

abstract class A : I

interface I {
    fun foo(): Int
}

class B : A() {
    override fun foo() = 42
}

val a1: A = B()

fun classOpenMethodCall_MonomorphicCallsite(): Int {
    var x = 0
    val a1 = a1
    var i = 0
    while (i < RUNS) {
        x += a1.foo()
        i++
    }
    return x
}

fun box(): String {
    var i = 0
    while (i < 10_000) {
        classOpenMethodCall_MonomorphicCallsite()
        i++
    }
    return "OK"
}
``` 

It compiled into the .wasm file and optimising with the next line:
wasm-opt --enable-nontrapping-float-to-int --enable-typed-function-references --enable-gc --enable-reference-types --enable-exception-handling --hybrid -O3 --inline-functions-with-loops --traps-never-happen --fast-math ./index.wasm -o ./indexOpt.wasm

Then the original and optimised versions are running with d8:
time d8 --experimental-wasm-gc --experimental-wasm-eh --module ./test.mjs

I see the next results:
NOT OPTIMISED: 23.75s user 0.03s system 100% cpu 23.760 total
BINARYENED: 82.83s user 0.06s system 99% cpu 1:22.95 total

The binaryen version is [b69d3a8](https://github.com/WebAssembly/binaryen/commit/b69d3a8fa0d6d7588811ef92067a48eed576e03f)
The d8 version is v8-mac64-rel-10.2.9
Platform is MacOs x86-64

All the compiled files (.wasm, .js and .wat) are placed [here](https://drive.google.com/file/d/1KJR0C5ftcIIodSsb0iYlO7AhOxccgMky/view).

Thank you.

**Comment by jakobkummerow** [comment]
I think something's weird there :slightly_smiling_face: . I'll take a closer look.

**Comment by igoriakovlev** [comment]
I have a bunch of such cases (about 80% of all our benchmark cases). I could prepare and share whole benchmark project with you or validate fixes for you one by one.

**Comment by jakobkummerow** [comment]
First finding: it's a microbenchmarking artifact. Binaryen inlined `classOpenMethodCall_MonomorphicCallsite` into `box`, and `box` is only called once. V8 does create optimized code for it early on, but never gets a chance to use that because it doesn't support on-stack replacement for Wasm and `box` never gets called again.

The easiest workaround would be to move the outer 10K loop to the JavaScript side. (Or at least split it further: about 10-100 calls from JS into Wasm should do the trick.)

Relatedly, I'd drop the iteration count a bit; 80 seconds is a long time to wait for a profiling run. 8s would be plenty.

Could you please also post the command-line to recreate the .wasm from .wat? Variations of `wasm-opt --enable-nontrapping-float-to-int --enable-typed-function-references --enable-gc --enable-reference-types --enable-exception-handling --hybrid -O3 --inline-functions-with-loops --traps-never-happen --fast-math ./index.wasm -o ./indexOpt.wasm` that take `index.wat` as input all seem to give me a Binaryen error message (about the `sub` keyword in the type definitions).

It  would be interesting to see if that change addresses all of the problem here. @kripken's `--no-liftoff` results might mean that there's more going on, a regression from 24 to 40 would still be unfortunate.

**Comment by igoriakovlev** [comment]
I replaced some count of outer iterations out from _box_ into JS side and seems the times for optimised and non-optimised wasm now close to each other:
### NOT OPTIMISED: 2.15s user 0.02s system 100% cpu 2.150 total
### BINARYENED: 1.71s user 0.02s system 101% cpu 1.716 total

The experiment can be found [here](/Users/igoryakovlev/Downloads/degradation/degradation2.zip)

I will try to put some special code into our benchmark framework to prevent payload inlining (for example to call the wasm payload function through JavaScript).

**Comment by igoriakovlev** [comment]
But anyway, according to me that the inliner should not be too aggressive in case of lack of OSR. So, is it still the issue or not?

**Comment by kripken** [comment]
In general our thinking has been that OSR is common in microbenchmarks but almost never happens in real-world code. So we have not made any effort to avoid this situation (since any such effort would have downsides by avoiding useful inlining in other cases). But if real-world data shows otherwise we should definitely reconsider.

An option btw is to build with less inlining by setting the relevant `wasm-opt` flags (also `-Os` or `-Oz` instead of `-O3` may be enough).

**Comment by jakobkummerow** [comment]
I find it hard to argue that the inliner was "too aggressive" here. Really, what you'd want is a rule "if a function is the outer loop of a benchmark driver, and only gets called from the outside once or twice, then nothing should get inlined into that function". But how do you reliably decide that a given function is the outer loop of a benchmark driver? If it has a loop with hard-coded upper limit that's a power of 10 between 1K and 1M? Obviously that would be very brittle and might easily have both false positives and false negatives. And what if you pass the limit as a parameter to the function? And how can Binaryen tell how often the function will get called from the outside?

Besides, it doesn't end there, because there are so many compiler optimizations that torpedo the usefulness of microbenchmarks. One of the most common examples is dead code elimination. A good compiler will optimize `for (var i = 0; i < 1000; i++) { 2 + 3; }` to nothing. But if you expected to be able to measure the performance of addition (`2 + 3`) that way, you'd be misled and/or disappointed. On the other hand, even if compilers had an oracle that could reliably detect microbenchmarks and disable optimizations, that also wouldn't be satisfactory: many microbenchmarks *want* to see whether certain optimizations happen, and what their impact is. So a better solution would be to have an ability to somehow mark ranges of code as "leave this exactly as it is" for the optimizer. But that would be an entire language feature whose _only_ purpose is microbenchmarks; that doesn't seem like a good idea either.

So, I think ultimately it will always be the responsibility of the authors of microbenchmarks (which is a position I also often find myself in) to write their benchmarks carefully, and investigate whether any effects they're seeing actually reflect what they wanted to measure, or are artifacts of the specific way in which the benchmark worked.

**Comment by igoriakovlev** [comment]
I am totally agree that the benchmarks of any kind must take responsibility to workaround any optimisations and platform specific behaviour. My question mostly connected with targeting of wasm platform itself, like is it targeting to hi-performance single-entry one-time running calculations (like math, bitcoin mining and whatnot) or there is no good applications (at least for now) that could be affected by the lack of stack replacement in wasm?

**Comment by kripken** [comment]
One big reason why this hasn't been an issue on the Web is that code has to return to the browser event loop fairly often (or else the browser shows a slow script dialog). It is true that Web Workers allow long-running code, though, but that hasn't been a problem in practice as it seems rare.

Possibly wasm off the Web will be different, however, that doesn't seem to be the case either so far: major use cases are things like edge compute which can just AOT compile the wasm - it's compiled once and then ready to quickly run when requests come in. Also, often the requests are short and throughput is actually less of a concern for them: One consequence of that is that while threading is a priority on the Web (for things like games, Photoshop, Google Earth), it is not really a priority for wasm on the server from all I hear.

There are other examples, though, like node.js running wasm as part of some long computation, but it just seems relatively rare so far.
