### ISSUE TITLE
[Builder / C-API] MemorySize and MemoryGrow now required pre-init memory, but this breaking change

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4946]
After multi-memory we now required setup memory before start of compilation which is not always possible. For example, Builder for `MemorySize` and `MemoryGrow` required pre-setup of memory: https://github.com/WebAssembly/binaryen/blob/main/src/wasm-builder.h#L668 otherwise it will fail with `Fatal: Module::getMemory: 0 does not exist`. But pretty often we should collect all data segments first by scan whole sources and later init memory. So now we have the typical chicken and egg problem in api. This problem can be solved in different ways, so I do not know which way is the most acceptable. For example, we can add a C-/JS- API that allows you to update the data segments after `BinaryenSetMemory`. Or checking `is64` inside `makeMemorySize` / `makeMemoryGrow` somehow in different way. I would like to point out that makeLoad and etc work fine and don't require any existing changes

**Comment by kripken** [comment]
Is the problem you don't know the size of memory before scanning segments in your source? If it's not that, then please explain in more detail what you need to do here that doesn't work.

**Comment by dcodeIO** [comment]
What we are essentially doing is:
1. Compile the program and collect element segments
2. Add the memory to the module

The issue is that code is generated in between 1 and 2 because we are reusing Binaryen's IR and don't have our own. The same problem arises for the type builder btw, where in between 1 and 2 we don't know the full type graph yet. That one is even more critical than memories I think (for memory we could perhaps use a dummy), as we'd need our own temporary IR to be able to use the type builder. Similar underlying challenge though, arising from our use of Binaryen as our backend with no layer in between.

**Comment by MaxGraey** [comment]
At this point we have the following flow for binaryen:

1) Build full Binaryen IR and handles data segments as they build
2) Read size of data segments from Binaryen IR
3) Add memory to IR (we know size of data segments now)

With the recent changes we have to do this now:

1) Add some stub memory to IR (with zero data segments)
2) Build full Binaryen IR
3) Update memory with data segments

The problem is that we can't update added memory with new data segments in p.3. 
We simply don't have an API for that. We should or remove specific memory (such API is missing) or update only data segments for specific memory (such API is missing as well).
