### ISSUE TITLE
const->add->load/store pattern not optimized

### ISSUE THREAD

**Issue by adrian17** [WebAssembly/binaryen#5076]
Just noticed LLVM issue https://github.com/llvm/llvm-project/issues/57771

And realized that wasm-opt doesn't optimize the `i32.const X -> i32.add -> i32.load_s 0` pattern to `i32.load_s X` either. I'm assuming optimize-instructions pass could handle a pattern like this?

**Comment by MaxGraey** [comment]
Binaryen should optimize this. It has `OptimizeAddedConstants` pass (`--optimize-added-constants` or `--optimize-added-constants-propagate`) for this:
https://github.com/WebAssembly/binaryen/blob/main/src/passes/OptimizeAddedConstants.cpp#L78

**Comment by adrian17** [comment]
Yeah, I just realized. Still, even if I pass it, it doesn't appear to work for me:
Before:
```
000285 func[3] <example_get1>:
 000286: 20 00                      | local.get 0
 000288: 41 80 80 c0 80 00          | i32.const 1048576
 00028e: 6a                         | i32.add
 00028f: 2d 00 00                   | i32.load8_u 0 0
 000292: 0b                         | end
```
After:
```
wasm-opt wasmtest.wasm -o wasmtest-opt.wasm -O -g --low-memory-unused
```
```
00027e func[3] <example_get1>:
 00027f: 20 00                      | local.get 0
 000281: 41 80 80 40                | i32.const 4293918720
 000285: 6b                         | i32.sub
 000286: 2d 00 00                   | i32.load8_u 0 0
 000289: 0b                         | end
```

Anyway, thank you; looks like either way, I can't use it currently.

**Comment by MaxGraey** [comment]
`--low-memory-unused` can handle only offset which less than `1024`. `1048576` definitely bigger than `1024`

**Comment by adrian17** [comment]
Too bad; thanks.

**Comment by kripken** [comment]
We can easily raise the current 1K limit. But in practice 1K handled 99% of cases in my tests, and there is a downside to raising it, since that space in the Memory is wasted.

But those measurements were a while ago - if we have benchmarks showing higher values can help, we can make the limit customizable.

**Comment by d0sboots** [comment]
I'm the person who filed https://github.com/llvm/llvm-project/issues/57771

This pass in binaryen can *never* address the issue there, because the solution requires encoding the base address of the variable in memory into the offset, and using the computed GEP offset as the "address" to the load/store. Since increasing the low-memory-limit pushes valid base addresses farther up, the applicability of the optimization will be forever out of reach.

**Comment by kripken** [comment]
@d0sboots Correct, only LLVM can do that I believe, because only it can assume that `data + $0` won't overflow (since it would be UB to read past the data's end). The Binaryen optimization is meant for other things, specifically loads from moderate-sized structs and arrays,
```wat
local.get 0
i32.const 42
i32.add
i32.load

=>

local.get 0
i32.load offset=42
```
(valid under the assumption of low-memory-unused), which is similar to comment 0 here.
