### ISSUE TITLE
Parse errors during `wasm-opt --print` should print out wat leading up to the parse error

### ISSUE THREAD

**Issue by eyebrowsoffire** [WebAssembly/binaryen#5344]
If `wasm-opt --print` encounters some kind of parse error (an opcode it doesn't recognize), it just bails and gives a single parse error. It would be really really nice if it would at least print out everything it had parsed up to that point anyway. This would help in a couple situations:

1) This would help people writing code generators localize their issue better, where exactly wasm-opt is unable to parse
2) For those of us working on the absolute bleeding edge, we are sometimes emitting opcodes that binaryen does not yet recognize, but it would be really helpful to at least be able to look at the types sections, imports/exports, globals and how they are encoded.

**Comment by kripken** [comment]
We could maybe find a way to skip functions that error, and print out other functions and global sections somehow. Is that what you're looking for? It might be a lot of work though, I don't know offhand.

Printing partial data *inside* a single function seems very hard though - once we see a bad opcode, we're totally confused, and even stuff we parsed before could be part of something that is still in a partial state. So that might not be feasible.

Btw, right now the error should mention the binary offset of the bad opcode - are you seeing that at least?

**Comment by eyebrowsoffire** [comment]
Yeah I think continuing to parse after an error is obviously not a really feasible request, since you don't even know what the length of the opcode is supposed to be for example. But my request is simply to just print out what has been parsed before the parse error was encountered, not to try to continue.

**Comment by kripken** [comment]
It looks like there is a simple way to add a flag to ignore function bodies. That way if you see an error you could run again with `--skip-function-bodies` and still be able to print out all the rest of the module. Would that be good enough for now?

(Skipping individual functions would be a larger chunk of work, I'm not sure yet how much.)

**Comment by eyebrowsoffire** [comment]
That would also be great. By the way, this isn't necessarily a burning fire (at least for me) at the current moment, it's just something that would make my life a bit easier when trying to isolate issues with our code generator.

**Comment by kripken** [comment]
It turns out there might be a simple way to show all the wasm that was read until the function where an error happens: https://github.com/WebAssembly/binaryen/pull/5356

**Comment by eyebrowsoffire** [comment]
Wow, amazing, thank you!
