### ISSUE TITLE
Function subtyping issue in SignatureRefining

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#5463]
```wat
(module
 (rec
  (type $A (func         (param (ref null $B)) (result (ref null $A))))
  (type $B (func_subtype (param (ref null $A)) (result (ref null $B)) $A))
 )

 (func $0 (type $A) (param $0 (ref null $B)) (result (ref null $A))
  (ref.func $0)
 )
)
```

STR:
```
wasm-opt -all --signature-refining a.wat
Fatal: Internal GlobalTypeRewriter build error: Heap type has an invalid supertype at index 1
```

cc @tlively

**Comment by tlively** [comment]
The problem is that the analysis infers that func `$0` always returns a non-nullable reference, so it tries to refine signature `$A` to return non-nullable `(ref $A)`. But it doesn't update `$B` to also return non-null, so `$B` is no longer a correct subtype of `$A`. The fix would be to do the same kind of analysis up and down the subtype hierarchy that `TypeRefining` does. In fact, it probably makes sense to combine `SignatureRefining` into `TypeRefining` so it can share that analysis.

**Comment by kripken** [comment]
Fuzzer found a variation on this:
```wat
(module
 (rec
  (type $type$1 (func (result (ref null $type$3))))
  (type $type$3 (array (mut (ref $type$1))))
  (type $type$0 (func (result (ref null $type$2))))
  (type $type$2 (func_subtype (result (ref $type$3)) $type$1))
 )
 (func $0 (type $type$0) (result (ref null $type$2))
  (unreachable)
 )
 (func $1 (type $type$1) (result (ref null $type$3))
  (ref.null none)
 )
)
```

**Comment by tlively** [comment]
wdyt about the fix of combining SignatureRefining into TypeRefining?

**Comment by kripken** [comment]
I'm not sure how to merge them exactly. Otherwise they seem quite orthogonal. But maybe I'm not seeing an idea you have?

I'd be ok with disabling refining of types that don't work yet, for now - like checking if there are subtypes perhaps?

**Comment by tlively** [comment]
The observation is that signature refining is just a special case of general type refining (because function signatures are types, too) and that correct signature refining requires all the analyses that typerefining already does.

**Comment by tlively** [comment]
Sounds good to skip optimizations for now and I can look into combining things later.
