### ISSUE TITLE
GC opcode compatibility with spec proposal

### ISSUE THREAD

**Issue by xujuntwt95329** [WebAssembly/binaryen#5553]
Hi, I'm using binaryen to generate some wasm modules with GC opcode, however I found that binaryen will generate some opcode which is not introduced in the [GC proposal](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#instructions-1), such as `array.new_fixed 0xfb1a`. I'm wondering:

1. Is there any flags to force binaryen to emit GC proposal compatible wasm module?
2. When will the new opcode introduced by binaryen be committed to spec proposal?
3. Is there a list of the incompatible opcodes between binaryen and spec proposal for every release?

Thanks a lot!

**Comment by tlively** [comment]
Please see https://bit.ly/3cWcm6Q for the prototype spec that is actually implemented by Binaryen, V8, and other projects. In general the opcodes used by implementations do not match the opcodes in the upstream spec documents because the implementations have to worry about maintaining backward compatibility and smooth upgrades for experimental users. There will be a period of breakage before WasmGC is finalized in which all of the opcodes will be changed to their final values, which will match the upstream spec.

**Comment by xujuntwt95329** [comment]
Thanks a lot! I'll close this issue.
