### ISSUE TITLE
Difference between Binaryen.js release and debug builds regarding BigInt

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#5647]
Debug builds of Binaryen.js (both JS and Wasm) seem to differ from Release builds, in that Debug builds appear to anticipate BigInt integration in the C ABI while Release builds do not.

Compiling the `binaryen_js` target using `-DCMAKE_BUILD_TYPE=Debug` fails at the end of compilation during `wasm2js` invocation:
```
[100%] Linking CXX executable bin/binaryen_js.js
em++: error: wasm2js does not support WASM_BIGINT
make[3]: *** [CMakeFiles/binaryen_js.dir/build.make:393: bin/binaryen_js.js] Error 1
make[2]: *** [CMakeFiles/Makefile2:363: CMakeFiles/binaryen_js.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:370: CMakeFiles/binaryen_js.dir/rule] Error 2
make: *** [Makefile:190: binaryen_js] Error 2
emmake: error: 'make -j12 binaryen_js' failed (returned 2)
```

Compiling the `binaryen_wasm` target using `-DCMAKE_BUILD_TYPE=Debug` works, but yields a binary where `_BinaryenLiteralInt64` expects a BigInt argument, not two number arguments (low and high bits), then failing at runtime when `_BinaryenLiteralInt64` is invoked with two number values:
```
TypeError: Cannot convert [some number] to a BigInt
  at file://path/to/binaryen_wasm.js:745:22
```

Compiling either using `-DCMAKE_BUILD_TYPE=Release` produces artifacts that do not assume BigInt integration.

Origin seems to be [in CmakeLists.txt](https://github.com/WebAssembly/binaryen/blob/0578862dc5569a4b544800d666458d698536a1a5/CMakeLists.txt#L310), where `-sWASM_BIGINT` is specified for Debug builds only.

**Comment by dcodeIO** [comment]
When just removing `-sWASM_BIGINT`, both the `binaryen_js` and `binaryen_wasm` targets fail to build, but with a different error:

```
[ 98%] Linking CXX executable bin/binaryen_js.js
em++: error: changes to the wasm are required after link, but disallowed by ERROR_ON_WASM_CHANGES_AFTER_LINK: ['path/to/wasm-emscripten-finalize', '-g', '--dyncalls-i64', '--pass-arg=legalize-js-interface-exported-helpers', '--dwarf', 'bin/binaryen_js.wasm', '-o', 'bin/binaryen_js.wasm']
note: to disable int64 legalization (which requires changes after link) use -sWASM_BIGINT
make[3]: *** [CMakeFiles/binaryen_js.dir/build.make:393: bin/binaryen_js.js] Error 1
make[2]: *** [CMakeFiles/Makefile2:363: CMakeFiles/binaryen_js.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:370: CMakeFiles/binaryen_js.dir/rule] Error 2
make: *** [Makefile:190: binaryen_js] Error 2
emmake: error: 'make -j12 binaryen_js' failed (returned 2)
```

When removing both `-sWASM_BIGINT` and `-sERROR_ON_WASM_CHANGES_AFTER_LINK`, both targets work, but `binaryen_js` with warnings:
```
warning: running pass 'flatten' which is not fully compatible with DWARF
warning: running pass 'flatten' which is not fully compatible with DWARF
```

Respective PR originally introducing the two flags: https://github.com/WebAssembly/binaryen/pull/4842

**Comment by kripken** [comment]
Looks like @aheejin asked why that difference was introduced back in that PR: https://github.com/WebAssembly/binaryen/pull/4842#pullrequestreview-1056172321

@dschuff do you remember why?

**Comment by dschuff** [comment]
Ah yeah, so #4842 was mostly intended to make it so the DWARF info was reliable (as well as representative of how we recommend users use debug info, and useful for testing changes in the debug info generation). So WASM_BIGINT is needed to avoid using Binaryen transforms at link time, and ERROR_ON_WASM_CHANGES_AFTER_LINK is there to ensure that such transforms don't get accidentally reintroduced (so having it raise the error when removing WASM_BIGINT is WAI).

But in that PR I failed to take the JS build into account at all, and I apparently missed Heejin's comment about the behavior difference.
So, what's the best way to fix this? Here are some constraints/considerations:
1. If we want the debug build to be debuggable with DWARF, we need WASM_BIGINT=1 in the debug build and SINGLE_FILE=0. (We may or may not actually care about debugging ourselves, but binaryen_wasm does still make a nice test case for wasm debug info. Even so it's not a super-critical use case so dropping it from the upstream build could be an option if the alternatives are really bad).
2. IIRC WASM_BIGINT=1 is the default for all wasm builds now since it's been shipped on all the browsers for a while; it has the advantage of faster link times and (maybe) a slight performance advantage for passing i64s across the wasm/js boundary. IMO it makes sense for the release build of binaryen_wasm to do that too, unless there's some reason not to.
3. Wasm2JS doesn't support WASM_BIGINT currently.

If we want to both 2 and 3, it sounds like we'll have to fix something. I guess we could make wasm2js support binaries built for bigint... we'd presumably just make wasm2js run the i64-export lowering pass (the one that that usually runs on the wasm) before the rest of the wasm2js pipeline? Then the JS-side code would always use bigint. But it's unclear to me how valuable that would be; are there engines that support bigint but not wasm? Or is there some other reason we want a JS-only build (other than supporting old engines)?
Alternatively we could use BIGINT=1 for wasm and =0 for JS. Then we'd have to make Binaryen's JS use of _BinaryenLiteralInt64 (and any other places?) be compatible with both. I don't think you can currently use emscripten preprocessor defines like WASM_BIGINT in user-written post-js but maybe there's another way.

**Comment by kripken** [comment]
Interesting. This is for DWARF debugging of Binaryen itself, correct? I guess in the past we were using it as a testcase. But if that's not needed then the simplest thing might be to turn off WASM_BIGINT.

Otherwise, if we need WASM_BIGINT, then things get tricky for all the reasons you mentioned. I don't think we need WASM_BIGINT + wasm2js, so using WASM_BIGINT when wasm might be the best option out of all those. (For the preprocessor issue, we can add runtime checks I think, though that's unpleasant...)

**Comment by dschuff** [comment]
AFAIK we don't actually need WASM_BIGINT, since probably nobody is using DWARF to debug Binaryen. I really just added it so that we could use Binaryen as a test case for debug info.
I can turn off WASM_BIGINT by default for the debug build. Maybe I'll leave it behind a default-off CMake flag to make it easy to test DWARF with the recommended flags. Probably it does make sense to keep SINGLE_FILE off in debug builds though? Otherwise there's not much point in having debug info at all.

**Comment by aheejin** [comment]
As @dschuff pointed out this is basically what we are using as a test case and I don't think anyone else is using it. Commenting the `WASM_BIGINT` and other necessary lines off and adding a little more comments in line with "Currently Binaryen's DWARF transformation has some issues so if you want DWARF testing without Binaryen please comment these lines off" sounds OK to me.

**Comment by kripken** [comment]
Sounds good, thanks, I opened #5654
