### ISSUE TITLE
`wasm-opt` adds `nop` instruction to empty exported function

### ISSUE THREAD

**Issue by Cyborus04** [WebAssembly/binaryen#5745]
Running `wasm-opt -Oz` or `wasm-opt -O4` on a module exporting an empty function adds an unnecessary `nop` instruction.

This:
```wat
(module
  (type (func))
  (func (type 0))
  (export "example" (func 0)))
```
becomes this:
```wat
(module
  (type (func))
  (func (type 0)
    nop)
  (export "example" (func 0)))
```

It's not a huge deal, but it seems strange to me that optimization (especially `-Oz`!) would grow the output even by one byte.

**Comment by kripken** [comment]
Good point, we should fix that. PR: #5746

This is something that we can't do in Binaryen IR, which is more structured than wasm, and has places where a nop is needed. I think that's why this wasn't noticed before, as we focus most of our work on Binaryen IR. But we can also optimize at the wasm stack level using StackIR as that PR does.
