### ISSUE TITLE
Explicit registration of passes required

### ISSUE THREAD

**Issue by jasonwilliams200OK** [WebAssembly/binaryen#577]
Punch line: MS-VCR build does not comply with UD behavior of GCC for static initialization

On Windows 10 with VS2015Update2, git2+ and cmake3+ in PATH, I built binaryen:

```cmd
git clone https://github.com/WebAssembly/binaryen.git --recursive
cd binaryen
cmake .
cmake --build . --config Release
```

When I tried running the hello world example: `bin/asm2wasm ./test/hello_world.asm.js` in Windows PowerShell, it gives me: `Fatal: Could not find pass: dce`.

Apparently, `dce` and many other passes do not get initialized; only print, print-minimized and print-full get attention of static initializer. This is because the compiler/linker are optimizing those code paths out as suspected by @kripken: https://github.com/WebAssembly/binaryen/pull/576#issuecomment-224125210.

I have confirmed this by placing `#pragma comment(linker, "/INCLUDE:wasm::registerPass")` after [asm2wasm.cpp#L29](https://github.com/WebAssembly/binaryen/blob/e4a81f9/src/tools/asm2wasm.cpp#L29) and using `/OPT:NOREF` switch, the linker throws:

> LNK2001	unresolved external symbol wasm::registerPass	asm2wasm

Similar case study: http://stackoverflow.com/q/9459980 (see Edit section of original post)

Interesting comments:

> 
* Relying on static initialization to register functions is probably a bit error prone in the long run. Have you considered just doing explicit registration?
* I think if you want something initialized, try to initialize them MANUALLY other than depending on compiler's work

**Comment by kripken** [comment]
They should be linked in by cmake, then used by the global constructors. On unix, we need some linking tricks since we use a static library which links in object files on demand, and they don't seem to be demanded (until the global constructor is seen). I don't know much about windows linking, does it also link in object files on demand?

**Comment by jasonwilliams200OK** [comment]
If this is achievable via CMake configuration, that would be pretty awesome.
Among all the "passes", only the `RegisterPass` in `Print.cpp` is getting called. I don't know how this one is not optimized away by the compiler. The rest of the passes code is optimized when building `asm2wasm`.

AFAIK, the linking is on demand with VC compiler in a way that if we want to keep those symbols alive (and tell the optimizer to back off), we would need to bring about certain configurations. I tried all the documented ways (setting `/Include` via pragma, setting /OPT:NOREF, turn of optimizers), but none of these worked. The static initilizers RegisterPass in all other passes source files except for Print.cpp don't get called. The robust approach suggested by commenters on the SO question (http://stackoverflow.com/q/9459980) is to either have the static registration code reachable or add a an custom registration function and explicitly call it after the translation unit executes.

@equalsraf, @sethjackson, @joncaves, @jkotas, could you guys suggest a better way to make linker force kick the static initializer with VC 2015? After running the `cmake .` config build command (https://github.com/WebAssembly/binaryen/issues/577#issue-158915795) I opened `binaryen.sln` in VS215, set `asm2wasm` as a start up project and put a breakpoint in `pass.cpp`'s ctor: https://github.com/WebAssembly/binaryen/blob/f6b5c1e/src/passes/pass.cpp#L33-L36. 

*ps - we are pursuing to incorporate experimental code generation for wasm in Core[RT/CLR]: https://github.com/dotnet/coreclr/issues/5303*

**Comment by binji** [comment]
I agree with the SO post; automatic registration in C++ seems nice on the surface, but it has always come back to bite me. Making it explicit makes it easy to tell what happens, when it happens. And you don't need any static initialization order hacks (i.e. singletons).

It looks like you already have an explicit list of passes in `pass.cpp` to run, by name -- IMO it would actually be nicer to move the names of the passes into this file so they aren't spread across multiple files.

Another idea: it seems like the `PassRegistrar` is used primarily for the benefit of `binaryen-shell`, so you can reference passes by name on the commandline. Why not move the name-to-pass mapping there? You could entirely remove the registrar, because it there would be no need to create a pass dynamically by name. This has other benefits as well, as you could make a parameterized pass without having to subclass to override the arguments, etc.

**Comment by kripken** [comment]
I guess I'm not totally opposed to adding a list by name somewhere, but I was hoping avoid it... it's annoying in LLVM that to add a pass you need to edit multiple files with boilerplate.

Passes are run not just by the shell, but also by asm2wasm for example. It's a general functionality I expect to be used in s2wasm as well eventually.

How about just making the library with passes a shared library as opposed to static? That would avoid the link hacks on linux. Would it work on windows?

**Comment by jasonwilliams200OK** [comment]
> Would it work on windows?

I think it has nothing to do with Windows as if we compile the code MingW compiler, it would work? But it is not working when *compiled* with VC++ compiler. The static initialization of dead code path is undefined behavior that is, for C++ compiler it is up to the implementer/vendor choice whether or not the optimizer should wipe out the code before static initialization happen. The implementation of binaryen is tied to GCC compiler's UD behavior. Unix/Windows is not the issue here.

> How about just making the library with passes a shared library as opposed to static?

Wouldn't it be too invasive to change it from static->shared just for readability problem, compared to *"hey, what if we have forward declaration of all the passes structs in `pass.h` which is included everywhere that matters, and we have forward-declared like half of them structs already there, why not all?"* :smile: 

Something like:

**pass.h** (already included by asm2wasm.cpp and all the other entry points of utilities)

```cpp
// Line 226 onwards

struct DeadCodeElimination : public WalkerPass<PostWalker<DeadCodeElimination, Visitor<DeadCodeElimination>>> {
  // forward declare the list of members here
};
static RegisterPass<DeadCodeElimination> registerPass("dce", "removes unreachable code");


struct DropReturnValues : public WalkerPass<PostWalker<DropReturnValues, Visitor<DropReturnValues>>> {
  // forward declare the list of members here
};
static RegisterPass<DropReturnValues> registerPass("drop-return-values", "stops relying on return values from set_local and store");

// and so on
```

then use scope resolution in code files `DeadCodeElimination.cpp` etc. while removing structs re-definitions.

**Comment by kripken** [comment]
Well, putting all the class definitions of all the passes in `pass.h` would make it very large. Some of those classes have many functions and properties. And it would sort of kill incremental compilation if adding a single pass means recompiling all the others (since they all include `pass.h`). But, maybe we can find some solution to all this.

However, what undefined behavior do you refer to? AFAIK we rely on a special linker flag, but everything should be defined. Specifically, we have a static lib with objects that each have a global constructor. The linker flag makes us link in all those objects. Then each's global constructor ensures it is not eliminated. This is exactly the same mechanism LLVM uses to declare commandline arguments, for example, and I was under the impression it is not undefined behavior?

**Comment by jasonwilliams200OK** [comment]
@kripken,when I was searching for similar flag for VC++, I found /OPT:NOREF optimizaiton and /INCLUDE linker flags of interest, but people were suggesting the behavior varies from compiler to compiler and that relying on static initialization to register objects is a bad idea in C++. Can you point me to C++ spec mandating the retention of static lib objects when optimizer has the opportunity to eliminate it as dead code? This way we will declare it as VC++ bug and report it to their bug tracker.

**Comment by kripken** [comment]
I didn't look in a spec for this, but

1. I have seen this pattern in other projects, like LLVM as mentioned, and I assumed it would be reasonable for them to do, since LLVM tends to make reasonable choices.
2. The LLVM optimizer will not remove code called by a global constructor. And LLVM tends to use UB to optimize, so when it doesn't usually that's for correctness.
3. And most importantly, it seems strange to remove code callable by a global constructor. For example a global C++ object whose constructor prints hello world - if we remove that, we no longer print it. So the optimizer would be changing observable behavior. That can't be right, can it? And that behavior is all we depend on here (except for linking actually including the object files, which we need a special flag for on linux).

**Comment by jasonwilliams200OK** [comment]
Sounds like "whatever LLVM does or doesn't" is a defacto standard over ISO. :smile: 
But at any rate, with this bug still lurking, the VC builds are broken in a false-positive manner. For future, we can probably setup AppVeyor CI configure (in addition to TravisCI) in order to avoid build breakage on Windows.

Thanks for your patience.

**Comment by juj** [comment]
https://github.com/WebAssembly/binaryen/pull/582 tries a minimal adjustment to pass linking to make this work.

**Comment by dschuff** [comment]
I'm in favor of doing something like #582 rather than making the registration magically use strings.

Regarding "whatever LLVM does":
LLVM tries to have it both ways, because it does have explicit `createFooPass()` calls but also tries to have auto-registration by name e.g. for `opt`. One reason they have the explicit way is because they need to support several different ways of building and linking all the passes (e.g. linking everything into a single DSO, and static linking with different archive libraries, etc) and support different platforms, so there ends up being some redundancy. Often you can get away with avoiding some of it for one use case but not for others. I think our use case is actually similar. If we intend for people to use parts of Binaryen in their own projects we have to support a variety of ways of linking, and that means having things more explicit. If we do the extra work to make things work with strings like in LLVM we can support that too, but I don't think it's worth it. I'd vote for just having `createFooPass()` for each pass and being done with it; it's a little extra boilerplate, but not that much, and it means things will just work. To me, our users are better served by giving them something that will more reliably work and be more tolerant of different environments than saving them a few lines of copy/paste.

As for things being defacto standard over ISO.... Well "whatever LLVM does" doesn't override ISO, but "whatever works on the platforms we care about" does :)

**Comment by kripken** [comment]
Good points, I guess I'm convinced on the #582 approach.

**Comment by jasonwilliams200OK** [comment]
Thanks @juj for the PR. Would also be nice to figure out or if some veteran Windows dev could point out that which flag to keep in our back pocket to make the static init magic happen in VCR for cases like these.

@dschuff, nice points, now we have working clang on Windows too so future is looking promising. ;)
