### ISSUE TITLE
Cannot build yew application via Trunk form docker image

### ISSUE THREAD

**Issue by drazen-todorovic** [WebAssembly/binaryen#6082]
While building from the docker image rust:1.73-bookworm, I am getting the following error:
```
22.51     2: error downloading archive file: 404
22.51        https://github.com/WebAssembly/binaryen/releases/download/version_113/binaryen-version_113-aarch64-linux.tar.gz
22.51 Error: error from HTML pipeline
22.51
22.51 Caused by:
22.51     0: error from asset pipeline
22.51     1: failed downloading release archive
22.51     2: error downloading archive file: 404
22.51        https://github.com/WebAssembly/binaryen/releases/download/version_113/binaryen-version_113-aarch64-linux.tar.gz

```

Can you please help?

**Comment by kripken** [comment]
We don't build aarch64 in our releases:

https://github.com/WebAssembly/binaryen/releases/tag/version_113

Looks like just `x86_64` atm.

The emsdk does build aarch64, though, so you might be able to get binaries from there. You'd need to download the entire emsdk though, so that's not ideal. It also isn't on every release yet, I think, but here is an example one: https://github.com/emscripten-core/emsdk/pull/1288

**Comment by kripken** [comment]
Wait, no, I didn't read the top lines in the release files, there is an arm64 one:

https://github.com/WebAssembly/binaryen/releases/download/version_113/binaryen-version_113-arm64-macos.tar.gz

Using that URL instead of

https://github.com/WebAssembly/binaryen/releases/download/version_113/binaryen-version_113-aarch64-linux.tar.gz

should work.

**Comment by drazen-todorovic** [comment]
Thanks for help 👍

**Comment by cmac4603** [comment]
How does someone change the URL that trunk uses? Running into the same issue on MacOS M2. Is it just to install with an instruction first and unpack the tar?
