### ISSUE TITLE
Generate Typescript 

### ISSUE THREAD

**Issue by ericvergnaud** [WebAssembly/binaryen#6145]
Hi,
thanks for the great work.
It seems that emscripten can now generate TypeScript ? See https://emscripten.org/search.html?q=typescript&check_keywords=yes&area=default ?
Would it make sense for binaryen to generate TypeScript instead of JavaScript ?
This would eliminate the risk of gaps between binaryen and binaryen.js.
Happy to try and make that happen if it makes sense (and I can get minimal support).

**Comment by tlively** [comment]
Emscripten doesn't really generate typescript, but rather a separate typescript definitions file that helps call Emscripten-generated JS from TS projects.

I'm not sure if you're thinking of compiling binaryen.js to TS or of implementing a `wasm2ts` tool that complements `wasm2js.` The former isn't possible because Emscripten doesn't emit typescript, although perhaps we could have it emit a TS definitions file for binaryen.js. The latter doesn't seem too useful because the TS output would only have extremely low level types that wouldn't be very useful for TS programmers.

Maybe the most useful thing to do here would be to create a TS definitions file for the binaryen.js API?

**Comment by ericvergnaud** [comment]
I'm not thinking about the how yet, just about the what i.e. have a single source of truth and move it as close as possible upstream. 
Right now, as I understand it, we have:
 - a js file hosted in Emscripten repo that is post-processed by being simply added to the binaryen_js.js file produced by Emscripten
 - a d.ts file hosted in Binaryen.js repo that wraps the generated binaryen_js.js. 
In an ideal world, we'd have a single Binaryen.ts file, hosted in Binaryen.js repo, and that would produce a binaryen_js.js and a binaryen_js.d.ts files.     
I don't yet know how to achieve that but if binaryen committers like the idea I'm happy to give it a try.

**Comment by tlively** [comment]
> * a js file hosted in Emscripten repo that is post-processed by being simply appended to the binaryen_js.js file produced by Emscripten

What file is this? Do you mean `binaryen.js-post.js` hosted here in the Binaryen repo?

> In an ideal world, we'd have a single Binaryen.ts file, hosted in Binaryen.js repo, and that would produce a binaryen_js.js and a binaryen_js.d.ts files

Are you referring to this binaryen.js repo? https://github.com/AssemblyScript/binaryen.js/

That repo is downstream from Binaryen and not maintained by us, so the base binaryen.js build from this repo should not depend on it.

**Comment by ericvergnaud** [comment]
> What file is this? Do you mean binaryen.js-post.js hosted here in the Binaryen repo?
Yes

> Are you referring to this binaryen.js repo? https://github.com/AssemblyScript/binaryen.js/

Oops typo. Just fixed it.

**Comment by tlively** [comment]
Ok, IIUC, you're proposing to add TS definitions to the upstream binaryen.js build here in the Binaryen repo. If so, that sounds good to me!

**Comment by ericvergnaud** [comment]
@tlively I just submitted the PR, so closing this.
