### ISSUE TITLE
wasm-merge deletes `unreachable` instruction when emitting text format.

### ISSUE THREAD

**Issue by doehyunbaek** [WebAssembly/binaryen#6219]
```wat
(module
(memory 1)
(func (export "_start") (;3480;) (param i32 i32) (result i32)
    local.get 0
    i32.load
    drop
    loop  ;; label = @1
      br 0 (;@1;)
    end
    unreachable)
)
```

```sh
# this is fine
~/binaryen-report/unreachable_missing wat2wasm unreachable.wat && wasm-merge unreachable.wasm bug -o merged.wasm && wasm-validate merged.wasm
# this is not fine
~/binaryen-report/unreachable_missing wat2wasm unreachable.wat && wasm-merge unreachable.wasm bug -S -o merged.wat && wat2wasm merged.wat
merged.wat:11:3: error: type mismatch in implicit return, expected [i32] but got []
  (loop $label$1
  ^
~/binaryen-report/unreachable_missing cat merged.wat
(module
 (type $0 (func (param i32 i32) (result i32)))
 (memory $0 1)
 (export "_start" (func $0))
 (func $0 (param $0 i32) (param $1 i32) (result i32)
  (drop
   (i32.load
    (local.get $0)
   )
  )
  (loop $label$1
   (br $label$1)
  )
 )
)
```

It seems the cause is that unreachable is missing in textual emit case.

Code is also at [this repo](https://github.com/doehyunbaek/binaryen-report/tree/master/unreachable_missing).

If this is a duplicate issue or non-issue, sorry in advance. Feel free to close the issue in that case.

**Comment by kripken** [comment]
This is expected behavior, but a little confusing, sorry about that.

First, this happens with just `wasm-dis` on such a binary, so it is not related to `wasm-merge` specifically:
```
$ bin/wasm-dis a.wasm
(module
 (type $0 (func (param i32 i32) (result i32)))
 (memory $0 1)
 (export "_start" (func $0))
 (func $0 (param $0 i32) (param $1 i32) (result i32)
  (drop
   (i32.load
    (local.get $0)
   )
  )
  (loop $label$1
   (br $label$1)
  )
 )
)
```
Second, the issue is that Binaryen's text format is different than the spec. Binaryen IR is more structured than wasm, and the text format it uses reflects that (for ease of debugging in Binaryen). In particular, in Binaryen that infinite loop has type `unreachable` and so it does not need to add another explicit `unreachable` afterwards. See the [docs](https://github.com/WebAssembly/binaryen/?tab=readme-ov-file#binaryen-ir) for more info, but the bottom line is you cannot expect the text format to interoperate between Binaryen and other tools. The binary format will always work, of course.

**Comment by doehyunbaek** [comment]
Sorry for false report, I just never expected the two text format would be different.

Thanks for such a quick and thoughtful reply. Closing.
