### ISSUE TITLE
Vanilla LLVM testing

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#67]
After https://github.com/kripken/emscripten/issues/4013 , we can test emcc+vanilla LLVM on our wasm-backend tests in this repo. That is, it would be nice if we detected we have emcc, and then run the full emcc tests using the wasm backend, and then optionally run the asm2wasm etc. tests that require a non-vanilla LLVM with the asm.js backend. To do that, we'd need to know emscripten's LLVM is vanilla, and if so, not run the asm.js tests, but still run the wasm-backend tests.

**Comment by kripken** [comment]
I am leaning towards checking an env var for LLVM. If it's present, we'll assume it's a stock/vanilla LLVM, and use that in `check.py`. Then on travis, we can download an LLVM+clang build from the waterfall and set the env var to find it.

We also need emcc, so we can add an emscripten submodule.

Thoughts? @jfbastien

**Comment by jfbastien** [comment]
Use `CC` and `CXX`?

**Comment by kripken** [comment]
But CC and CXX are set for clang or gcc. This would be a secondary compiler.

**Comment by jfbastien** [comment]
Oh so you have `CXX=emcc` already? `check.py` isn't using that envvar, but `emcc` is?

`CC2` and `CXX2`? ;-)

**Comment by kripken** [comment]
No, I mean, look at `.travis`. It already uses CC and CXX. We need an additional LLVM build aside from that.

But maybe we don't need an env var. I can just make check.py (or update.py?) grab LLVM+clang from the bot, put it in a dir, and use that with emcc. Could that work?

**Comment by jfbastien** [comment]
Here's my current thinking. I'm figuring things out with you, so I'm not 100% confident, LMK what you think!

I think `update.py` should be used to update things that are checked in (like `test/revision`, the submodule hashes, and the `.s` tests). I *really* don't want us to be checking in binaries like LLVM (or their tarball).

We could download the following archive: `https://storage.googleapis.com/wasm-llvm/builds/git/wasm-binaries-$(cat test/revision).tbz2`

Maybe add that archive to `.gitignore` as well as the folder it untars to, and then?

`check.py` could do that download I guess? First check if present, if it is do nothing, otherwise download and untar? Some of that logic is in `update.py`, so maybe it should be shared. Or maybe `update.py` could have an option to only download from what's already in `test/revision` (right now it only contains the bot revision, I could put the full content of `lkgr` instead).

**Comment by kripken** [comment]
Yeah, that sounds reasonable.

**Comment by jfbastien** [comment]
Would you like `test/revision` to contain more information on the build? Right now lkgr contains the following: https://gist.github.com/jfbastien/90c6f10d2a834927ad13

**Comment by kripken** [comment]
I don't currently see a need for more.

**Comment by kripken** [comment]
This is all implemented in #112, so we can discuss details there.
