### ISSUE TITLE
How to BinaryenCallRef

### ISSUE THREAD

**Issue by gotocoffee1** [WebAssembly/binaryen#6718]
Hello I am trying to use BinaryenCallRef but its not clear how. Unfortunately there is no example in c-api-kitchen-sink or other docs.
I tried it this way:
```cpp
  BinaryenAddFunction(mod, "name", BinaryenTypeCreate(nullptr, 0), BinaryenTypeCreate(nullptr, 0), nullptr, 0, BinaryenUnreachable(mod));
  auto exp = BinaryenRefFunc(mod, "name", BinaryenTypeFuncref());
  exp      = BinaryenCallRef(mod, exp, nullptr, 0, BinaryenTypeFuncref(), false);

  BinaryenAddFunction(mod, "name2", BinaryenTypeCreate(nullptr, 0), BinaryenTypeCreate(nullptr, 0), nullptr, 0, exp);
   
```
But the end boss is always [this](https://github.com/WebAssembly/binaryen/blob/main/src/wasm/wasm.cpp#L995) assert,

Any tips how I should use it or should I go back to `call_indirect` for now?

**Comment by kripken** [comment]
The assertion is because a `ref.func` must have the proper signature type in the IR, and not `funcref` which is a generic type. To fix that you need to create a signature type and use it there.

I opened a PR with an example of `BinaryenCallRef` now: #6721. The PR also adds a way to get the signature type from a function, which makes things easier. Without that you'd need to use the TypeBuilder API to get the type.
