### ISSUE TITLE
s2wasm doesn't output imports with the correct signature

### ISSUE THREAD

**Issue by binji** [WebAssembly/binaryen#68]
See 20000112-1.c.s.wast for example:
```
(module
  (memory 0 4294967295)
  (import $exit "env" "exit")
  (export "main" $main)
  (func $main (result i32)
    (call_import $exit
      (i32.const 0)
    )
    (unreachable)
  )
)
;; METADATA: { "asmConsts": {},"staticBump": 0 }
```
It should be ``(import $exit "env" "exit" (param i32))``

**Comment by kripken** [comment]
Thanks, fixed.

One possibly tricky issue is ignored return values. Since .s files no longer define imports, we must detect the type implicitly. But if an import has a return type, if might be ignored, in which case we will think it's a void function. Not sure if that's a problem or not. cc  @sunfishcode

**Comment by sunfishcode** [comment]
LLVM is currently prefixing `call` with return types, like `i32.call`. Does that address the concern here?

**Comment by kripken** [comment]
Oh right, yes, that should be fine. Even if the return value is ignored, it'll still be `i32.call`, right? Then that's fine, s2wasm reads the type of the call node here.

**Comment by sunfishcode** [comment]
Yes, the type prefix is there even when the return value is ignored.
