### ISSUE TITLE
Roundtrip-text fuzz bug with shared types

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#6850]
The attached wasm validates, but after conversion to text it becomes invalid,

```bash
$ bin/wasm-opt -all a.wasm --print > a.wat
warning: no output file specified, not emitting output
$ bin/wasm-opt -all a.wat
[wasm-validator error in function 0] function body type must match, if function returns, on 
(ref.func $0)
Fatal: error validating input
```
[a.wasm.gz](https://github.com/user-attachments/files/16662869/a.wasm.gz)

cc @tlively

**Comment by tlively** [comment]
Hmm, I can't reproduce the validation failure. Is this the expected wat?

```
(module
 (type $0 (shared (func (result (ref null (shared func))))))
 (elem declare func $0)
 (func $0 (type $0) (result (ref null (shared func)))
  (ref.func $0)
 )
)
```

The declarative segment does have the wrong type here, but the validation error you're seeing isn't about that.

**Comment by tlively** [comment]
Ah, it's because we only emit the `(type $0)` before the function parameters and results when GC is enabled, but that's necessary in the case to ensure the function type is shared. Will fix. In the long run, we might want to use shared-everything threads (and shared functions in particular) without enabling GC for e.g. Emscripten.
