### ISSUE TITLE
Flatten pass removes block results required by `br_on_*` instructions

### ISSUE THREAD

**Issue by tanishiking** [WebAssembly/binaryen#6924]
WasmGC introduces new instructions: [br_on_cast, br_on_cast_fail, br_on_non_null](https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md#casts). These instructions branch to a specified label, passing the operand with a target type.

For example, in the following code, `(br_on_non_null $labelNotNull (local.get $x))` branches to the (outside of) `block $labelNotNull` with the value `(ref $obj)` on the stack if `$x` is non-null.

When we apply the `flatten` pass to the code contains those instructions, the pass emits an invalid code:

```wasm
(module
 (type $obj (struct))
 (func $f (export "f")
  (param $x (ref null $obj))
  (result (ref null $obj))
  (block $labelNotNull (result (ref null $obj))
   (br_on_non_null $labelNotNull
    (local.get $x)
   )
   (local.get $x)
  )
 )
)
```

```wasm
$ wasm-opt -all --flatten test.wat -S -o -
[wasm-validator error in function f] break type must be a subtype of the target block type, on
(block $labelNotNull
 (local.set $1
  (local.get $0)
 )
 (br_on_non_null $labelNotNull
  (local.get $1)
 )
 (local.set $2
  (local.get $0)
 )
 (local.set $3
  (local.get $2)
 )
)
Fatal: error after opts
```

It is invalid because, while the break type of `br_on_non_null` is `ref $obj`, the block type is notype(?).

related: https://github.com/WebAssembly/binaryen/issues/6724

Should we lower `br_on_non_null` into `ref.is_non_null` and something, or can we somehow keep the block type through flatten pass?

**Comment by kripken** [comment]
This is a current limitation of flatten, I believe. In general the idea of flatten was to remove block results in order to simplify the IR. But things like `br_on_*` fundamentally require block results. So we'd need to either change the goal of flatten, or lower `br_on_*` into branches and locals, using `ref.is_non_null` etc., as you said, though that would be less efficient code, unfortunately.

I'm curious what you are using flatten for? In Binaryen itself we've used it in wasm2js, but that isn't important for WasmGC code anyhow (since wasm2js doesn't support GC in general, yet, and no current plans to).

**Comment by tanishiking** [comment]
Thanks @kripken. I'm interested in using `flatten` for `LoopInvariantCodeMotion`. I've noticed that while LICM moves entire expressions, it doesn't move nested sub-expressions, and it seems that flattening helps LICM as commented:
https://github.com/WebAssembly/binaryen/blob/432ed1ccc62aea8c04ac0d2f89a25acedde6c948/src/passes/LoopInvariantCodeMotion.cpp#L21-L22
https://github.com/WebAssembly/binaryen/blob/432ed1ccc62aea8c04ac0d2f89a25acedde6c948/src/passes/LoopInvariantCodeMotion.cpp#L212-L213

I'm not yet sure how impactful LICM is on our artifact (generated from the Scala.js wasm-backend), I'm just exploring how LICM moves our code 😄 

Also, I tried to flatten on compiler side (by inserting `local.set` and `local.get`), but couldn't make binaryen IR flattened, and not sure it's flattened structure survives through `-O` passes.

**Comment by kripken** [comment]
I see, interesting.

About licm, it is not enabled by default because in practice it doesn't seem that helpful: VMs will do licm themselves, and it makes the code larger (it adds locals), so in general it increases size without speeding things up. Though, it might help baseline tiers and interpreters, perhaps.  But I'd be interested to hear thoughts or data otherwise!

> not sure it's flattened structure survives through -O passes.

Hmm, yeah, in general the passes will "un-flatten" as that is more efficient. You might experiment with running licm as the first pass, though. (But, again, I am not sure how useful licm is, as I mentioned above.)

**Comment by tanishiking** [comment]
> in practice it doesn't seem that helpful: VMs will do licm themselves, and it makes the code larger (it adds locals), so in general it increases size without speeding things up.

Thanks, that’s interesting. It seems like it's better to leave LICM optimizations to the VMs. 

We recently moved the `itables` implementation from a mutable array to an immutable struct in [this PR](https://github.com/scala-js/scala-js/pull/5038), and I've noticed some performance improvements in loop-heavy benchmarks (I'm not sure if these gains are directly due to LICM optimizations by the VMs, though).

I'll close the issue for now. Thank you very much, @kripken, for answering my questions!
