### ISSUE TITLE
Unsubtyping fuzz bug

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#6935]
```wat
(module
 (type $0 (sub (array (mut i8))))
 (type $1 (func (result f32)))
 (rec
  (type $2 (sub (array nullref)))
  (type $3 (sub (array i8)))
  (type $4 (struct (field (mut i8))))
  (type $5 (sub (array (mut i8))))
 )
 (rec
  (type $6 (sub final $5 (array (mut i8))))
  (type $7 (sub $0 (array (mut i8))))
 )
 (export "func_16" (func $0))
 (func $0 (result f32)
  (drop
   (ref.cast (ref $7)
    (array.new_default $0
     (i32.const 71)
    )
   )
  )
  (f32.const 0)
 )
)
```

```bash
$ bin/wasm-opt w.wat -all --fuzz-exec --unsubtyping
[fuzz-exec] calling func_16
[trap cast error]
[fuzz-exec] calling func_16
[fuzz-exec] note result: func_16 => 0
[fuzz-exec] comparing func_16
[fuzz-exec] optimization passes changed results
```

**Comment by tlively** [comment]
This bug is way more interesting than I expected. Here's a reduced test case:

```
(module
  (type $super (sub (array (mut i8))))
  (type $sub (sub $super (array (mut i8))))
  (func $0 (export "test")
    (drop
      (ref.cast (ref $sub)
        (array.new_default $super
          (i32.const 0)
        )
      )
    )
  )
)
```
Unsubtyping analyzes the module and decides it's safe to remove the subtyping relationship. There is nothing wrong there because the cast should fail just the same before and after removing the subtyping. Then it goes to rewrite and update the types. Remember, only private types are ever rewritten. It turns out that we unconditionally consider `(type (sub (array (mut i8))))` to be public because it is one our "ignorable" public types. So only the `$sub` gets rewritten. It is rewritten to not have a supertype anymore, so it becomes `(type (sub (array mut i8)))`. This is the same type as `$super`! Normally this wouldn't be a problem because there would be multiple rewritten types that would all be together in a big rec group, so `$sub` and `$super` would still be different types, but in this case there is only the single private type, so we get a conflict. The module is updated so that `$sub` and `$super` are the same type and the cast starts succeeding incorrectly.

The immediate fix is to remove `(type (sub (array (mut i8))))` as an ignorable public type since the js-string-builtins proposal settled on `(type (array (mut i8)))` as the type used in string builtins instead. But this is an instance of a more general problem we might run into as we allow more open-world optimizations. In general there is nothing stopping the rec group of rewritten types from conflicting with some public rec group. To avoid this, the more robust solution would be to do what we do in MinimizeRecGroups: try a different permutation of the types, and if there are no more permutations, add a brand type.
