### ISSUE TITLE
Godot Game Engine WebAssembly startup time and other issues

### ISSUE THREAD

**Issue by eska014** [WebAssembly/binaryen#824]
I recently added WebAssembly compilation to the build system of [Godot Engine](https://github.com/godotengine/godot). Running works in Chromium and (with some checks compiled out) in Firefox.

However, **startup time after download takes around 10 seconds**. Is there some way to decrease this time on Godot's side? Is this being improved on the browsers' side?

Other issues we're having with WebAssembly:

 - Compiling with `s2wasm` currently terminates with this message:

       Fatal: Error: linked module is not valid.

   So far I have only succeeded in compiling per `asm2wasm`.

 - As mentioned above, running in Firefox currently does not work, giving this error:

       failed to compile wasm module: TypeError: imported Memory with incompatible size

   When compiling Firefox with [`CheckLimits()` in `WasmModule.cpp`](https://hg.mozilla.org/mozilla-central/file/f37699322f20/js/src/wasm/WasmModule.cpp#l710) modified to always return `true`, running in Firefox works.

**Comment by kripken** [comment]
How is the startup time compared to asm.js? If it's worse, then something is wrong. One possibility is that the wasm binary is in a side file, and downloaded separately, so webserver performance matters more - how are you testing?

The s2wasm issue is a bug in the wasm backend or s2wasm, can you provide the bitcode file? That should be enough to reproduce the problem.

The Memory issue is strange - Firefox and Chrome should be running the same checks. What is `TOTAL_MEMORY` at compile time? Do you modify memory size during startup, perhaps? And, is this with or without memory growth?

**Comment by eska014** [comment]
> How is the startup time compared to asm.js? If it's worse, then something is wrong. One possibility is that the wasm binary is in a side file, and downloaded separately, so webserver performance matters more - how are you testing?

On Firefox, asm.js startup takes about 25 seconds, 3 seconds when cached. Firefox occasionally locks up for a minute when starting Godot per asm.js though, so it can take much longer, usually on the first time testing. WebAssembly startup takes about 10 seconds, so definitely faster.

On Chromium, asm.js startup takes about 4 seconds, I guess due to caching. Between `Ctrl+Shift+Del`, 'Disable Cache' in DevTools, Icognito mode and `Ctrl+F5`, nothing seems to disable/delete the asm.js cache, so no idea about times when running uncached. WebAssembly startup takes about 15 to 20 seconds.

By startup time, I mean compilation+engine initialization, without download time.

I suppose there's no caching for WebAssembly? I'm also surprised about Chromium's compilation speed, taking up to twice as long as Firefox in worst cases.

I've been testing with both 1) a server in the same country 2) locally per `python -m SimpleHTTPServer`. All files involved are hosted on the same server, in the same directory. We're using Emscripten's loading code by using emcc's `--shell-file` option.
I'm subtracting the download time displayed in each browser's devtools from all times though.

Here are examples of Godot per asm.js and WebAssembly:
 - http://godot.eska.me/temp/asmjs-2dplatformer
 - http://godot.eska.me/temp/wasm-2dplatformer

===

>The s2wasm issue is a bug in the wasm backend or s2wasm, can you provide the bitcode file? That should be enough to reproduce the problem.

Sorry, the error with s2wasm was caused by a configuration mistake on my end, I'm now getting this error:

```
Assertion failed: (!estack.empty()), function operator(), file src/s2wasm.h, line 713.
```

The new bitcode files are here if still relevant:
 - http://godot.eska.me/temp/emcc-0-basebc.bc.xz
 - http://godot.eska.me/temp/emcc-1-linktime.bc.xz

===

> The Memory issue is strange - Firefox and Chrome should be running the same checks. What is TOTAL_MEMORY at compile time? Do you modify memory size during startup, perhaps? And, is this with or without memory growth?

We explicitly define `TOTAL_MEMORY` in the HTML file before running. The value is set by game developers during export of their game within the engine's editor, I've been testing with 268435456. Memory growth is not enabled.

**Comment by lars-t-hansen** [comment]
Re startup time, Firefox has a faster compiler for wasm (the "baseline" compiler) that is not yet in use but which is still present in recent builds.  I'd be curious to know what compilation+initialization times you're seeing if you use this compiler.  You can enable it by setting javascript.options.wasm_baselinejit to *true* in about:config.

**Comment by eska014** [comment]
@lars-t-hansen Wow, baseline compiler give very nice results, taking 3 to 4 seconds. But the tab crashes after the first few frames of the game are rendered. This is still on Firefox with the memory checks compiled out, otherwise I continue to get `imported Memory with incompatible size`.

===

If I remove the explicit `TOTAL_MEMORY = 268435456` from the HTML, this is what I get:
 - Firefox, standard compiler: Tab crashes before rendering a frame of the game
 - Firefox, baseline compiler: `Cannot enlarge memory arrays. [...]`
 - Chromium: `Cannot enlarge memory arrays. [...]`

**Comment by lars-t-hansen** [comment]
Crash with standard compiler logged: https://bugzil.la/1316321.

**Comment by lukewagner** [comment]
@eska014 Chrome doesn't have any asm.js caching that I know of; I expect godot might be missing the Chromium asm.js pseudo-AOT optimization path and thus the compilation is happening at runtime and that's the difference you're seeing.  Otherwise asm.js-on-Chrome would be slower then WebAssembly-on-Chrome.

However, WebAssembly actually supports *explicit* caching by storing compiled `WebAssembly.Module` objects in IDB using `IDBObjectStore.put` and `get`.  On FF, I've measured this to be significantly faster than asm.js caching.  (Note: until [bug 1312808](https://bugzilla.mozilla.org/show_bug.cgi?id=1312808) is fixed, cached `Module`s get invalidated when the FF build-id updates, this should be fixed soon and before release.)

**Comment by kripken** [comment]
> I'm now getting this error: Assertion failed: (!estack.empty()), function operator(), file src/s2wasm.h, line 713.

Sounds like #828 perhaps, which was fixed in upstream LLVM just now.

> We explicitly define TOTAL_MEMORY in the HTML file before running. [..] Memory growth is not enabled. 

I see. I think what's happening is that without memory growth, we set the wasm initial and max memory size to `TOTAL_MEMORY` as seen at compile time. If you set it to something higher, that surprises the JS engine.

The wasm spec bakes the max memory size into the binary, so our only options here are to enable memory growth. If you do that, does it work? If so, we should figure out how to show a better error here.

**Comment by lars-t-hansen** [comment]
https://bugzil.la/1316156 has been fixed and will presumably show up in Nightlies in a day or two.

**Comment by kripken** [comment]
#834 adds a warning with guidance to turn on memory growth for the memory size incompatibility issue.

**Comment by eska014** [comment]
You're right, compiling with `-s ALLOW_MEMORY_GROWTH=1` fixes the issue. I'm also no longer getting crashes with the baseline-compiler, not sure if this related to memory growth or changes to the baseline-compiler since I last compiled.
Are there significant optimizations we're missing out on by enabling memory growth?

As for `s2wasm`, I recompiled LLVM and the error does seem to be gone. I'm now getting this:

    Fatal: Unknown relocation: __environ

There's no such name in Godot, looks like it comes from Emscripten.

@lukewagner
> Chrome doesn't have any asm.js caching that I know of

That explains it, I was assuming it works similar to Firefox. Thanks for the tip about explicit caching, I'll give it a try.

> godot might be missing the Chromium asm.js pseudo-AOT optimization path

Is there something we can do about this in Godot?

@lars-t-hansen
Thanks for the update on the crash, I recompiled Firefox and confirm it no longer crashes.

**Comment by jgravelle-google** [comment]
The "unknown relocation: environ" is probably one of the known failures: https://github.com/kripken/emscripten/blob/incoming/tests/test_core.py#L4615
It seems to be an internal emscripten/binaryen thing (s2wasm not being aware of the things in library.js because of an ordering/forwarding mismatch, is my current theory)

Currently s2wasm isn't quite ready for production use, so I fear you'll run into more issues for a while with it. I'd actually really like to see what those issues *are*, so I appreciate you trying it, but I don't want you to set your expectations too high just yet.

webassembly.org doesn't mention s2wasm at all (aside from a few mentions of the "upcoming upstream LLVM wasm backend"), but binaryen's README.md doesn't make it very clear that it's still experimental. Should we reword that to be more explicit?

**Comment by eska014** [comment]
@jgravelle-google Thanks for the warning. I'm aware that `s2wasm` is still rather WIP though, I'm reporting these failures with the prospect of hitting a new wall after an error is resolved.

But I agree that one could easily get the wrong idea about the state of the LLVM-backend path from Binaryen's readme.

By the way, I also think it would be helpful to note in Binaryen's readme that one needs to set a CMake option to compile the WebAssembly backend in LLVM (`LLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly` if I remember correctly). Took me a bit to realize the first time.

**Comment by kripken** [comment]
@eska014 "Are there significant optimizations we're missing out on by enabling memory growth?"

For wasm, not much. It may reserve more memory than it needs, but for a full game engine like Godot I imagine it's fine. And there is no speed downside unlike with asm.js.

**Comment by kripken** [comment]
About the README, it refers to the emscripten wiki page, which mentions the wasm backend isn't stable yet (but I'm ok if people want to update the README too). I updated [the wasm backend page](https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend) to mention that cmake flag.

**Comment by eska014** [comment]
Saw that there were changes to the linker, so tried building with s2wasm again. Build finishes successfully, now I'm getting this error when startingruntime:
```
failed to compile wasm module: TypeError: import object field 'emscripten_asm_const_int' is not a Function`
```

I assume it's this issue: WebAssembly/design#769

@kripken Thank you, we've enabled memory growth for WebAssembly builds.

**Comment by eska014** [comment]
Tried s2wasm again with the `EM_ASM` PRs merged. The build terminates from s2wasm, printing this:

```
[[object_alias:]]:
==========
__dso_handle, 1
        .import_global  __environ
        .size   __environ, 
==========
```

**Comment by jgravelle-google** [comment]
That looks similar to failure we're seeing on the wasm waterfall https://wasm-stat.us/builders/linux/builds/16834/steps/Link%20LLVM%20Torture%20with%20s2wasm/logs/stdio
(More general wasm waterfall link: https://wasm-stat.us/console)

This is due to some recent churn in what the LLVM backend is emitting that s2wasm doesn't support yet. The `EM_ASM` change fixes a post-s2wasm failure, so this just a regression as opposed to uncovering new failure.

If you wanted to try with the `EM_ASM` change but not the breaking LLVM change, I currently have the following revisions:
LLVM - git hash fd07c4c7b5350fa8a0aa91e4248f0023638db5d8, subversion revision 295840
clang - git hash a745be5724ad975e8456500c52f12d7ef2995770, subversion revision 295843
Which should be compatible with latest emscripten/binaryen.

Thanks for trying it again!

**Comment by eska014** [comment]
Rebuilt LLVM with those commits and the build finishes successfully again.
When running, I'm now getting an undefined reference error for `asm["setTempRet0"]` in the generated .js file, in the definition of `function _saveSetjmp`. Changing the call to `Module.asm["setTempRet0"]` gets rid of the error.

With that change, I get a failing assertion `assert(offset_high === 0)` in syscall140 (`llseek`) from here: https://github.com/kripken/emscripten/blob/04255b4ada1983301cb35cafbc5483db036149fe/src/library_syscall.js#L663

If I comment that assert out, the game starts and runs. That's great, thanks for the help so far!

I notice the size of the binary generated by asm2wasm (~14.3MiB) is smaller than that generated by s2wasm (~15.4MiB), how comes?

**Comment by dschuff** [comment]
I expect it's mostly just that asm2wasm has had a lot more optimization
effort put into it than upstream LLVM  wasm backend has. s2wasm doesn't run
any optimizations itself. You could try running wasm-opt over the output
from s2wasm (it's a wasm->wasm optmizer that does the same optimizations
that asm2wasm uses).

**Comment by kripken** [comment]
Yeah, can try the binaryen optimizer on s2wasm output, e.g. `wasm-opt -Os input.wasm -o output.wasm`. I'd be curious to know by how much it helps on your codebase, but currently it probably won't do a lot because the wasm backend's output isn't coordinated with binaryen's optimizer (it's pretty "final" - binaryen would need to undo some things to really do serious optimization).

**Comment by eska014** [comment]
Gave it a try with s2wasm+wasm-opt, here are the results. Using release builds now, I forgot I was using debug builds for the previous comparison

```
asm2wasm:   13591777
s2wasm -O:  14723647
s2wasm -Os: 14723647
s2wasm -Oz: 14723647
s2wasm -O2: 14729818
s2wasm -O3: 14729818
s2wasm -O1: 14730066
s2wasm:     15563060
s2wasm -O0: 15668791
```

That's already a nice improvement. I'll keep my fingers crossed for optimizations in the LLVM backend.

**Comment by eska014** [comment]
What's going on with Chrome 57-stable? WebAssembly is enabled, but won't start:

    LinkError: WebAssembly.instantiate(): Import #3 module="env" function="___dso_handle" error: global import must be a number

WebAssembly support is only mentioned in the 57-beta change log, not for 57-stable. Is it not officially supported yet? Or is this an issue in the build?

Works in Chrome Canary 59.0.3037.0.
It also works in Firefox 52 =)

**Comment by eska014** [comment]
WebAssembly is working fine in our development-branch at this point, and I don't want to leave this issue open forever.
Thank you very much for your help! I'll open a new issue if we happen upon any concrete issues.

In the coming months we'll release Godot Engine 3.0 (currently in alpha) with WebAssembly export and hopefully get some real-world feedback.

**Comment by kungfooman** [comment]
@eska014 TL;DR: try restarting Chrome

Just had the same error message, basically from one code change to the other... Chrome worked for weeks and is/was my main WASM testing plattform. Had no clue what could even cause it, since I reverted the change, recompiled, reloaded... still had this error. So the compiled binaries were fine. After wasting more and more time, to figure out the case, I tested a minimal `main() { printf("..."); }` example and it still failed with the `___dso_handle` error. Tested same generated test.html/test.wasm in Firefox and it worked without any issues. So I knew Chrome didn't work right for some reason. After a Chrome restart everything worked fine again... so in my case I ran into some Chrome bug, cannot reproduce it (yet) tho.
