### ISSUE TITLE
Eliminate unnecessary (if_else (i32.ne exp 0) ..) patterns.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#85]
Seeing a few (if_else (i32.ne exp 0) ..) style patterns in the asm2wasm output. These are in the original asm.js, but were they needed there for some reason and should they be eliminated in the conversion, or just artifacts that can be ignored? These turn up in br_if and if_else in the zlib benchmark. Some are not direct but deeper in expressions that return a value to a predicate argument.

Example asm.js, but not sure if this generated the above pattern on conversion.
```
   do {
    i11 = i11 + -2 | 0;
    i9 = HEAPU16[i11 >> 1] | 0;
    HEAP16[i11 >> 1] = i9 >>> 0 < i2 >>> 0 ? 0 : i9 - i2 & 65535;
    i10 = i10 + -1 | 0;
   } while ((i10 | 0) != 0);
```

**Comment by kripken** [comment]
I don't see `if_else` with `ne` as an argument in that output. Just a `br` with one.

It would be very helpful if the testcases were complete, btw - to check this, I had to embed in a file and write some code around it. I might have written something there that makes my result not match yours. It is always better to have the simplest, most direct steps so that I can see what you are seeing.

**Comment by kripken** [comment]
Based on an email testcase, this looks like an issue at the asm.js stage, and has been optimized in emscripten.
