### ISSUE TITLE
Binaryen validator incorrectly requires drop after void call.

### ISSUE THREAD

**Issue by eholk** [WebAssembly/binaryen#876]
I'm getting the following error:
```
[wasm-validator error in function $main] unexpected false: non-final block elements returning a value must be drop()ed (binaryen's autodrop option might help you), on 
(block $bb2
  (call $panic)
  (unreachable)
)
```
The `$panic` function has type `(func)`, so it should not require anything to be dropped. Furthermore, my understanding is that `unreachable` is supposed to automatically empty stack.

I have a binaryen API trace available here: https://gist.github.com/eholk/098eb194392bb04d80db561fe228c849

The full module in wast format, as outputted by binaryen is here: https://gist.github.com/eholk/a9cf2a5cc4340ed5dde991792f3ee4b1#file-gistfile1-txt-L399

When I modify mir2wasm to surround the call by a drop, it passes the binaryen validator, but then V8 complains that we are trying to drop when there is nothing on the stack.

**Comment by kripken** [comment]
Hmm, can you run it with `BINARYEN_PRINT_FULL=1` in the env? (that prints out the types while printing) I think you'll see `[i32] (call $panic)`, because you have `BinaryenCall(the_module, "panic", operands, 0, 1);`, and the last param is the return type, and 1 is `i32`.

The API requires you to set the function type when creating it, and also state the type when creating call nodes to it, because they can be created in parallel. We check that they match at the end, but I suspect after the error that you see, so you see this first.

**Comment by eholk** [comment]
I updated the gist. You are correct. It looks like mir2wasm was mapping types incorrectly.
