### ISSUE TITLE
mir2wasm, but no ir2wasm?

### ISSUE THREAD

**Issue by procedural** [WebAssembly/binaryen#878]
Mozilla syndrome?

**Comment by kripken** [comment]
No connection to mozilla, "MIR" in Rust means "Middle-level Intermediate Representation". It's in between a high-level Rust AST and a low-level machine IR.

**Comment by procedural** [comment]
@kripken cool, so, um, how's other languages which can spit only IR can target wasm?

**Comment by dschuff** [comment]
By "IR" do you mean LLVM IR? If so, then they would use the LLVM WebAssembly backend. Currently it converts LLVM IR into a text .s file, which Binaryen's `s2wasm` tool can convert to wast.

**Comment by procedural** [comment]
@dschuff yes, llvm ir. so `ir` -> `.s` -> `.wasm`, ok, cool, why we need `.s` at all here once again?

**Comment by kripken** [comment]
Also, for the general case of a compiler or IR that wants to compile to wasm, Binaryen has a C API - which is how mir2wasm works in fact. The API tries to be as simple as possible to use. Here are the [docs](https://github.com/WebAssembly/binaryen/wiki/Compiling-to-WebAssembly-with-Binaryen). If you try it out, feedback is very welcome.

**Comment by procedural** [comment]
@kripken good to know, thanks.

still not sure why we need `.s` here at all given that ir can generate it. what was the rationale behind `.s` format i and possibly other developers don't care about?

**Comment by dschuff** [comment]
It's not so much a rationale as a limitation. We were working on bringing up the LLVM backend before the wasm binary format was finalized, and also it's much easier to make LLVM emit something that looks like assembly that something that looks like the wast text format, especially as it was when we started. Now that the binary format is mostly settled, we are working on adding binary format support to LLVM, which will eliminate the need for a text format (although one will continue to exist, since it's useful for various things like testing).

**Comment by procedural** [comment]
> Now that the binary format is mostly settled, we are working on adding binary format support to LLVM, which will eliminate the need for a text format (although one will continue to exist, since it's useful for various things like testing).

Everything I wanted to hear, thanks! This makes sense, the issue can be closed now
