### ISSUE TITLE
asm2wasm - bad parseExpression state

### ISSUE THREAD

**Issue by ghost** [WebAssembly/binaryen#881]
hey,
I was playing with some asm.js code and i wanted to convert it into wasm using binaryen.
The parser throw this error (i simplified the code just for the example):

```javascript
bad parseExpression state:
==========
;
 var bd2 = bd | 0;
```

for the code:

```javascript

function testfunc(ab, bd) {
	ab = ab | 0;
	bd = bd | 0;
	var gg = 0; {
		var bd1 = bd | 0;
		var bd2 = bd | 0;
		var bd3 = bd | 0;
	};
}
```

**Comment by kripken** [comment]
Our asm.js parser isn't very good with error messages, sorry about that.

Here the problem is that that isn't valid asm.js - the extra `{` and `};` break the rules of how vars work (they must be one after the other, nothing in the middle), and also `var X = Y;` must have `Y` equal to zero, not an expression.

It would be good to improve our parsers error handling, if someone is interested.

**Comment by yancybulski** [comment]
sorry,
this is the original code (part of it), and it's running with asm.js...the brwoser didn't said anything about it not being valid

```javascript
function Lb(aa, da) {
	aa = aa | 0;
	da = da | 0;
	var zb = 0; {
		zb = Ya[(Va + ((aa >>> 12) << 2)) >> 2] | 0;
		if ((zb | 0) == -1) {
			Kb(aa, da);
		} else {
			Wa[aa ^ zb] = da;
		}
	};
}
```

**Comment by kripken** [comment]
That does look like valid asm.js, yes. How does binaryen handle it?

**Comment by yancybulski** [comment]
```javascript
bad parseExpression state:
==========
;
 var bd2 = bd | 0;
```

for the code:

```javascript

**Comment by kripken** [comment]
Hmm, then probably it's a bug in the asm.js parser. It's been tested in asm.js backend output, which doesn't emit unnecessary `{, };`s as in that code.

Would be good to fix but I don't know offhand how easy it would be.

**Comment by tlively** [comment]
asm2wasm no longer exists.
